import { coverage } from '../core/i18n.js';
import type { CoverageLine } from '../core/i18n.js';
import type { Finding, VibewardIntent } from '../core/types.js';
import type { SiteFiles, BrokenAsset } from '../http/crawl.js';
import type { ConsoleError } from './console.js';

// Website quality & AI-visibility checks. Everything here is pure: the network layer
// hands over the crawled HTML and this module only measures absences — the tag that is
// not there, the file that was never generated. That is exactly what a site generated by
// an AI and published untouched looks like.

/** Window for the <head> signals (title, meta, link, lang, JSON-LD). They live up front. */
const MAX_HTML = 200 * 1024;

/** Window for the body signals (<h1>, <img>, visible text). A guard against OOM, not a scan limit. */
const MAX_DOC = 5 * 1024 * 1024;

/** A page with less visible text than this is an empty shell, not a page. */
const EMPTY_HTML_CHARS = 200;

/** Uncompressed JS above this is a slow first paint on a phone. */
const HEAVY_BUNDLE_BYTES = 1_048_576;

/** Signals evaluated by `fingerprintStack`. Fixed so the score reads the same everywhere. */
const FINGERPRINT_TOTAL = 12;

/** Free hosting subdomains — nobody ships a real business on one on purpose. */
const PLATFORM_DOMAINS = [
  'vercel.app',
  'netlify.app',
  'lovable.app',
  'bolt.new',
  'pages.dev',
  'github.io',
  'web.app',
  'firebaseapp.com',
  'replit.app',
  'onrender.com',
  'surge.sh',
];

/** The crawlers that decide whether a site can be quoted inside an AI answer. */
const AI_BOTS = [
  'GPTBot',
  'OAI-SearchBot',
  'ChatGPT-User',
  'ClaudeBot',
  'anthropic-ai',
  'Claude-Web',
  'PerplexityBot',
  'CCBot',
  'Google-Extended',
  'Applebot-Extended',
  'Bytespider',
  'meta-externalagent',
];

export interface PageSignals {
  url: string;
  title: string | null;
  metaDescription: string | null;
  canonical: string | null;
  ogTitle: string | null;
  ogImage: string | null;
  lang: string | null;
  h1Count: number;
  jsonLdBlocks: number;
  imgTotal: number;
  imgWithoutAlt: number;
  faviconLink: boolean;
  bodyTextLength: number;
  /**
   * Bytes of inline `<script>` in the document — the JavaScript that never appears as a
   * separate bundle because it is written straight into the HTML. A hand-rolled or heavily
   * inlined app can ship megabytes this way, and it is worse than an external bundle of the
   * same size: it cannot be cached across pages and it blocks the HTML parser until it is
   * fully downloaded. The heavy-payload check counts it alongside the external bundles.
   */
  inlineScriptBytes: number;
}

export interface StackFingerprint {
  host: string;
  platformDomain: string | null;
  framework: string | null;
  clientRendered: boolean;
  /** The signals that fired, in English. `localizeFingerprint` swaps these for `signalsEs`. */
  signals: string[];
  /**
   * The same signals in Spanish, dropped by `localizeFingerprint` once one of the two has
   * been chosen — a report and a payload never carry both.
   */
  signalsEs?: string[];
  score: number;
  total: number;
}

// ---------------------------------------------------------------------------
// HTML parsing — regex on purpose. Bundler output is predictable markup and a
// real parser would be a dependency for no extra signal.
// ---------------------------------------------------------------------------

function clean(value: string | null | undefined): string | null {
  if (value === null || value === undefined) return null;
  const text = value.replace(/\s+/g, ' ').trim();
  return text.length > 0 ? text : null;
}

/** All opening tags of one element, as raw strings, so attributes can be read off them. */
function tagsOf(html: string, name: string): string[] {
  return html.match(new RegExp(`<${name}\\b[^>]*>`, 'gi')) ?? [];
}

function attr(tag: string, name: string): string | null {
  const m = tag.match(new RegExp(`\\b${name}\\s*=\\s*("([^"]*)"|'([^']*)'|([^\\s"'>]+))`, 'i'));
  if (!m) return null;
  return m[2] ?? m[3] ?? m[4] ?? '';
}

function stripComments(html: string): string {
  return html.replace(/<!--[\s\S]*?-->/g, ' ');
}

/**
 * Drops script, style and noscript bodies. Anything counted from the page body has to run
 * on this: a React bundle inlined in the page is full of `<h1>` and `<img>` inside strings,
 * and counting those turns "this page has no heading" into a lie about a client's site.
 */
function stripInert(html: string): string {
  return html.replace(/<(script|style|noscript)\b[^>]*>[\s\S]*?<\/\1>/gi, ' ');
}

/**
 * Bytes inside `<script>` tags that have no `src` — the JavaScript inlined into the document
 * rather than loaded as a separate file. A `src`-carrying script has an empty body, so it
 * contributes nothing; a `type="application/ld+json"` block is data, not code, and is skipped.
 */
function inlineScriptBytes(html: string): number {
  let total = 0;
  const re = /<script\b([^>]*)>([\s\S]*?)<\/script>/gi;
  let m: RegExpExecArray | null;
  while ((m = re.exec(html)) !== null) {
    const attrs = m[1] ?? '';
    if (/\bsrc\s*=/i.test(attrs)) continue;
    if (/\btype\s*=\s*["']?[^"'>]*(?:ld\+json|json|importmap)/i.test(attrs)) continue;
    total += Buffer.byteLength(m[2] ?? '', 'utf8');
  }
  return total;
}

/** Visible text: comments, script/style/noscript bodies and every tag removed. */
function visibleTextLength(html: string): number {
  return stripInert(stripComments(html))
    .replace(/<[^>]+>/g, ' ')
    .replace(/\s+/g, ' ')
    .trim().length;
}

export function parsePage(html: string, url: string): PageSignals {
  // Comments go first: markup left commented out is not markup, and starter templates
  // are full of commented-out meta tags.
  //
  // Two windows, on purpose. `doc` is the cheap one for everything that lives in <head>.
  // Body signals get `full`, because a Next.js RSC payload or an inline critical-CSS block
  // routinely pushes the real <h1> past 200 KB — and reading a page as heading-less because
  // the scanner stopped early is a false accusation in a report someone paid for.
  const full = stripComments(html.slice(0, MAX_DOC));
  const doc = full.slice(0, MAX_HTML);
  const visible = stripInert(full);

  let metaDescription: string | null = null;
  let ogTitle: string | null = null;
  let ogImage: string | null = null;
  for (const tag of tagsOf(doc, 'meta')) {
    const key = (attr(tag, 'name') ?? attr(tag, 'property') ?? '').toLowerCase();
    const content = clean(attr(tag, 'content'));
    if (!key || !content) continue;
    if (key === 'description') metaDescription ??= content;
    else if (key === 'og:title') ogTitle ??= content;
    else if (key === 'og:image') ogImage ??= content;
  }

  let canonical: string | null = null;
  let faviconLink = false;
  for (const tag of tagsOf(doc, 'link')) {
    const rels = (attr(tag, 'rel') ?? '').toLowerCase().split(/\s+/);
    if (rels.includes('canonical')) canonical ??= clean(attr(tag, 'href'));
    if (rels.includes('icon') || rels.includes('apple-touch-icon') || rels.includes('mask-icon')) {
      faviconLink = true;
    }
  }

  const images = tagsOf(visible, 'img');

  return {
    url,
    title: clean(doc.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]),
    metaDescription,
    canonical,
    ogTitle,
    ogImage,
    lang: clean(attr(doc.match(/<html\b[^>]*>/i)?.[0] ?? '', 'lang')),
    h1Count: (visible.match(/<h1(?:\s[^>]*)?>/gi) ?? []).length,
    // Read off `doc` and not `visible`: this is the one signal carried BY a <script> tag.
    jsonLdBlocks: tagsOf(doc, 'script').filter((t) =>
      (attr(t, 'type') ?? '').toLowerCase().includes('ld+json'),
    ).length,
    imgTotal: images.length,
    // `alt=""` is the deliberate "decorative image" marker, so only a missing attribute counts.
    imgWithoutAlt: images.filter((t) => attr(t, 'alt') === null).length,
    faviconLink,
    bodyTextLength: visibleTextLength(full),
    // Measured from the whole document, not the size-capped `full`: the point of this signal
    // is a payload big enough to be a problem, so it must not be capped away.
    inlineScriptBytes: inlineScriptBytes(html),
  };
}

// ---------------------------------------------------------------------------
// Stack fingerprint
// ---------------------------------------------------------------------------

function hostOf(url: string): string {
  try {
    return new URL(url).hostname;
  } catch {
    return url;
  }
}

function detectFramework(html: string): string | null {
  if (/\/_next\//.test(html)) return 'Next.js';
  if (/__NUXT__|\/_nuxt\//.test(html)) return 'Nuxt';
  if (/__sveltekit|\/_app\/immutable\//i.test(html)) return 'SvelteKit';
  if (/___gatsby|\/page-data\/|gatsby-chunk-mapping/i.test(html)) return 'Gatsby';
  if (/astro-island|data-astro/i.test(html)) return 'Astro';
  if (/\/static\/js\/main\.[0-9a-f]{6,}\.js/i.test(html)) return 'Create React App';

  const viteEntry = /\/assets\/index-[A-Za-z0-9_-]{6,}\.js/.test(html);
  const moduleScript = tagsOf(html, 'script').some(
    (t) => /module/i.test(attr(t, 'type') ?? '') && /\bcrossorigin\b/i.test(t),
  );
  if (viteEntry || moduleScript) {
    return /id=["']root["']|data-reactroot|__REACT_DEVTOOLS/.test(html) ? 'Vite + React' : 'Vite';
  }
  return null;
}

/**
 * Scores how much this looks like "generated by an AI and published without a second pass".
 * `files` is optional because two of the twelve signals (sitemap.xml, llms.txt) cannot be
 * seen in the HTML; when it is absent those two are simply never counted against the site —
 * an undercount is honest, guessing them from markup would not be.
 */
export function fingerprintStack(
  homeHtml: string,
  homeUrl: string,
  jsBytes: number,
  files: SiteFiles | null = null,
): StackFingerprint {
  // parsePage gets the whole document and picks its own windows; pre-truncating here would
  // hand it a body that stops at 200 KB and make `clientRendered` fire on a full page.
  const page = parsePage(homeHtml, homeUrl);
  const doc = stripComments(homeHtml.slice(0, MAX_HTML));
  const host = hostOf(homeUrl);
  const platformDomain = PLATFORM_DOMAINS.find((d) => host === d || host.endsWith(`.${d}`)) ?? null;
  const hasScriptSrc = tagsOf(doc, 'script').some((t) => attr(t, 'src') !== null);
  const clientRendered = page.bodyTextLength < EMPTY_HTML_CHARS && hasScriptSrc;

  const found: CoverageLine[] = [];
  const signal = (on: boolean, en: string, es: string): void => {
    if (on) found.push(coverage(en, es));
  };

  signal(
    Boolean(platformDomain),
    `Still on the default *.${platformDomain} domain`,
    `Todavía en el dominio *.${platformDomain} por defecto`,
  );
  signal(
    clientRendered,
    'HTML carries no content — JavaScript renders everything',
    'El HTML no trae contenido — JavaScript lo renderiza todo',
  );
  signal(!page.title, 'No <title>', 'Sin <title>');
  signal(!page.metaDescription, 'No meta description', 'Sin meta description');
  signal(!page.ogTitle && !page.ogImage, 'No Open Graph tags', 'Sin etiquetas Open Graph');
  signal(!page.canonical, 'No canonical URL', 'Sin URL canónica');
  signal(page.jsonLdBlocks === 0, 'No structured data', 'Sin datos estructurados');
  signal(Boolean(files && !files.sitemapXml), 'No sitemap.xml', 'Sin sitemap.xml');
  signal(!page.faviconLink && !(files?.faviconOk ?? false), 'No favicon', 'Sin favicon');
  signal(!page.lang, 'No lang on <html>', 'Sin lang en <html>');
  signal(Boolean(files && !files.llmsTxt), 'No llms.txt', 'Sin llms.txt');
  signal(
    jsBytes > HEAVY_BUNDLE_BYTES,
    `JavaScript over 1 MB (${formatBytes(jsBytes)})`,
    `JavaScript por encima de 1 MB (${formatBytes(jsBytes)})`,
  );

  return {
    host,
    platformDomain,
    framework: detectFramework(doc),
    clientRendered,
    signals: found.map((l) => l.en),
    signalsEs: found.map((l) => l.es),
    score: found.length,
    total: FINGERPRINT_TOTAL,
  };
}

// ---------------------------------------------------------------------------
// robots.txt
// ---------------------------------------------------------------------------

interface RobotsRule {
  allow: boolean;
  path: string;
}

interface RobotsGroup {
  agents: string[];
  rules: RobotsRule[];
}

/**
 * Groups the file the way a crawler does: consecutive `User-agent` lines share the rules
 * that follow, and the first rule line closes the agent list of that group.
 */
function parseRobots(text: string): RobotsGroup[] {
  const groups: RobotsGroup[] = [];
  let current: RobotsGroup | null = null;
  let takingAgents = false;

  for (const raw of text.split(/\r?\n/)) {
    const line = (raw.split('#')[0] ?? '').trim();
    if (!line) continue;
    const m = line.match(/^([A-Za-z-]+)\s*:\s*(.*)$/);
    if (!m) continue;
    const field = m[1]!.toLowerCase();
    const value = m[2]!.trim();

    if (field === 'user-agent') {
      if (!current || !takingAgents) {
        current = { agents: [], rules: [] };
        groups.push(current);
      }
      current.agents.push(value.toLowerCase());
      takingAgents = true;
    } else if (field === 'allow' || field === 'disallow') {
      if (current) current.rules.push({ allow: field === 'allow', path: value });
      takingAgents = false;
    } else if (field !== 'sitemap' && field !== 'host') {
      takingAgents = false; // crawl-delay & friends belong to the group but end its agent list
    }
  }
  return groups;
}

function blocksEverything(rules: RobotsRule[]): boolean {
  // `Disallow:` empty allows everything; `Disallow: /$` only hides the home page.
  const disallowsRoot = rules.some((r) => !r.allow && /^\/\**$/.test(r.path.trim()));
  if (!disallowsRoot) return false;
  // A narrower `Allow:` re-opens part of the site. Calling that "blocked" would tell an
  // owner they are invisible to ChatGPT when they are not — the worst mistake this file
  // can make, so the tie always goes to "not blocked".
  return !rules.some((r) => r.allow && r.path.trim().startsWith('/'));
}

/**
 * Blocks that a CDN injects into robots.txt on the way out, wrapped in its own markers.
 *
 * These matter because the remediation is a different action in a different place. Cloudflare
 * turned its managed AI-crawler block on for a very large number of zones, so the file the
 * owner opens in their repo either does not contain the rule or is not the copy being served,
 * and "delete the Disallow line" sends them looking for something that is not there.
 */
const MANAGED_ROBOTS: { vendor: string; begin: RegExp; end: RegExp; where: string }[] = [
  {
    vendor: 'Cloudflare',
    begin: /^#\s*BEGIN\s+Cloudflare\s+Managed\s+content/i,
    end: /^#\s*END\s+Cloudflare\s+Managed\s+content/i,
    where:
      "the Cloudflare dashboard for this zone, under AI Crawl Control / the managed robots.txt setting — not in the site's own `robots.txt`",
  },
];

/** A vendor-injected robots.txt block and the agents declared inside it. */
export interface ManagedRobots {
  vendor: string;
  /** Where the owner has to go to change it, in prose. */
  where: string;
  /** Lower-cased `User-agent` values declared between the markers. */
  agents: Set<string>;
}

/** The vendor block in a robots.txt, if the file carries one. */
function detectManagedRobots(text: string): ManagedRobots | null {
  for (const m of MANAGED_ROBOTS) {
    let inside = false;
    let found = false;
    const agents = new Set<string>();
    for (const raw of text.split(/\r?\n/)) {
      const line = raw.trim();
      if (m.begin.test(line)) {
        inside = true;
        found = true;
        continue;
      }
      if (m.end.test(line)) {
        inside = false;
        continue;
      }
      if (!inside) continue;
      const ua = /^user-agent\s*:\s*(.+)$/i.exec(line);
      if (ua) agents.add(ua[1]!.trim().toLowerCase());
    }
    if (found) return { vendor: m.vendor, where: m.where, agents };
  }
  return null;
}

export interface RobotsVerdict {
  /** The watched AI crawlers this file actually shuts out. */
  bots: string[];
  /** Whether the ban comes from the `User-agent: *` group — measured, never inferred. */
  viaWildcard: boolean;
  /** The `User-agent` values whose group carries the offending `Disallow`. */
  blockingAgents: string[];
  /**
   * The vendor block, when one exists and at least one blocking agent is declared inside it.
   * `covers: 'all'` means editing the repo's file changes nothing at all.
   */
  managed: { vendor: string; where: string; covers: 'all' | 'some' } | null;
}

/** The watched AI crawlers that this robots.txt actually shuts out. */
export function robotsBlocksAI(robotsTxt: string | null): string[] {
  return analyzeRobots(robotsTxt).bots;
}

/**
 * Who is blocked and, just as importantly, *where the block is written*. Deducing the
 * source from the count ("all twelve blocked, so it must be the wildcard") is wrong on the
 * most common shape there is: twelve per-bot groups plus a permissive `User-agent: *`. Get
 * that wrong and the report describes a line the file does not contain, while the suggested
 * fix rewrites rules the owner does want.
 */
export function analyzeRobots(robotsTxt: string | null): RobotsVerdict {
  const empty: RobotsVerdict = {
    bots: [],
    viaWildcard: false,
    blockingAgents: [],
    managed: null,
  };
  if (!robotsTxt) return empty;
  // A soft 404 (the SPA's index.html served for /robots.txt) is not a robots policy.
  if (/^\s*(<!doctype|<html)/i.test(robotsTxt)) return empty;

  const groups = parseRobots(robotsTxt);
  const wildcard = groups.filter((g) => g.agents.includes('*'));
  const wildcardBlocks = wildcard.length > 0 && blocksEverything(wildcard.flatMap((g) => g.rules));

  const bots: string[] = [];
  const named = new Set<string>();
  for (const bot of AI_BOTS) {
    const own = groups.filter((g) => g.agents.includes(bot.toLowerCase()));
    // A group naming the bot wins outright: it is never merged with the `*` group.
    if (own.length > 0) {
      if (blocksEverything(own.flatMap((g) => g.rules))) {
        bots.push(bot);
        named.add(bot);
      }
      continue;
    }
    if (wildcardBlocks) bots.push(bot);
  }

  const blockingAgents = [...named];
  if (wildcardBlocks && bots.length > named.size) blockingAgents.push('*');

  // Only a vendor block that actually contains part of the ban changes the remediation. A
  // managed section that carries unrelated rules is none of this finding's business.
  const vendor = detectManagedRobots(robotsTxt);
  let managed: RobotsVerdict['managed'] = null;
  if (vendor && blockingAgents.length > 0) {
    const insideCount = blockingAgents.filter((a) => vendor.agents.has(a.toLowerCase())).length;
    if (insideCount > 0) {
      managed = {
        vendor: vendor.vendor,
        where: vendor.where,
        covers: insideCount === blockingAgents.length ? 'all' : 'some',
      };
    }
  }

  return {
    bots,
    viaWildcard: wildcardBlocks && bots.length > named.size,
    blockingAgents,
    managed,
  };
}

// ---------------------------------------------------------------------------
// Findings
// ---------------------------------------------------------------------------

/**
 * Every check this module can emit, in report order. `checkWeb` only returns failures,
 * so the report needs this list to also show what passed — "6 of 18 checks passed" is
 * the line an owner acts on, and a report of nothing but problems reads as noise.
 * Keep in sync with the ids emitted below.
 */
export const WEB_CHECKS: { id: string; label: string; es: string }[] = [
  {
    id: 'web_robots_blocks_ai',
    label: 'robots.txt lets AI crawlers in',
    es: 'robots.txt deja entrar a los rastreadores de IA',
  },
  {
    id: 'web_ai_block_incomplete',
    label: 'AI crawlers blocked as declared',
    es: 'Rastreadores de IA bloqueados como se declaró',
  },
  { id: 'web_empty_html', label: 'HTML carries real content', es: 'El HTML trae contenido real' },
  { id: 'web_broken_assets', label: 'No broken assets', es: 'Sin recursos rotos' },
  {
    id: 'web_console_errors',
    label: 'No JavaScript errors on load',
    es: 'Sin errores de JavaScript al cargar',
  },
  {
    id: 'web_duplicate_titles',
    label: 'Each page has its own <title>',
    es: 'Cada página tiene su propio <title>',
  },
  { id: 'web_missing_title', label: '<title> present', es: '<title> presente' },
  { id: 'web_missing_meta_description', label: 'Meta description', es: 'Meta description' },
  { id: 'web_missing_og', label: 'Open Graph tags', es: 'Etiquetas Open Graph' },
  { id: 'web_missing_canonical', label: 'Canonical URL', es: 'URL canónica' },
  {
    id: 'web_missing_structured_data',
    label: 'Structured data (JSON-LD)',
    es: 'Datos estructurados (JSON-LD)',
  },
  {
    id: 'web_h1_structure',
    label: 'Exactly one <h1> per page',
    es: 'Exactamente un <h1> por página',
  },
  { id: 'web_missing_sitemap', label: 'sitemap.xml', es: 'sitemap.xml' },
  { id: 'web_missing_llms_txt', label: 'llms.txt', es: 'llms.txt' },
  {
    id: 'web_missing_lang',
    label: 'lang attribute on <html>',
    es: 'Atributo lang en <html>',
  },
  { id: 'web_missing_alt', label: 'Images have alt text', es: 'Las imágenes tienen texto alt' },
  {
    id: 'web_missing_404',
    label: 'Unknown URLs return 404',
    es: 'Las URLs inexistentes devuelven 404',
  },
  { id: 'web_missing_favicon', label: 'Favicon', es: 'Favicon' },
  { id: 'web_heavy_bundle', label: 'JavaScript under 1 MB', es: 'JavaScript por debajo de 1 MB' },
];

/**
 * Checks this crawl had no way to evaluate, each with the reason, keyed by check id.
 *
 * A check that could not fail on the input it was given has not passed. "Every page has its
 * own title ✅" on a crawl that reached one page is a fact about arithmetic, not about the
 * site, and it lands in the report next to genuine passes and inside the "12 of 17 passed"
 * count — which is how a report ends up sounding more thorough than the scan was. These are
 * reported as not evaluated instead, on the same footing as the console check with no
 * browser behind it.
 *
 * Deliberately separate from the config's `notApplicable`, which is the owner declaring a
 * check irrelevant. This one is vibeward declaring its own coverage.
 */
export function webChecksNotEvaluated(input: {
  pages: PageSignals[];
  assetsChecked: number;
}): Map<string, CoverageLine> {
  const { pages, assetsChecked } = input;
  const reasons = new Map<string, CoverageLine>();
  const n = pages.length;

  if (n < 2) {
    reasons.set(
      'web_duplicate_titles',
      coverage(
        `only ${n} page crawled — needs at least 2`,
        `solo se rastreó ${n} página — hacen falta 2`,
      ),
    );
  }
  if (pages.reduce((total, p) => total + p.imgTotal, 0) === 0) {
    reasons.set(
      'web_missing_alt',
      coverage('no <img> found on the crawled pages', 'no se encontró ningún <img> en las páginas'),
    );
  }
  if (assetsChecked === 0) {
    reasons.set(
      'web_broken_assets',
      coverage('no referenced assets to request', 'no había recursos referenciados que pedir'),
    );
  }

  return reasons;
}

function formatBytes(bytes: number): string {
  if (bytes >= 1024 * 1024) return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
  if (bytes >= 1024) return `${Math.round(bytes / 1024)} KB`;
  return `${bytes} B`;
}

function ofPages(n: number, total: number): string {
  return `${n} of ${total} page${total === 1 ? '' : 's'}`;
}

function ofPagesEs(n: number, total: number): string {
  return `${n} de ${total} página${total === 1 ? '' : 's'}`;
}

function urlsOf(pages: PageSignals[]): string[] {
  return pages.map((p) => p.url);
}

function originOf(pages: PageSignals[]): string {
  const home = pages[0];
  if (!home) return 'https://example.com';
  try {
    return new URL(home.url).origin;
  } catch {
    return 'https://example.com';
  }
}

export function checkWeb(input: {
  pages: PageSignals[];
  files: SiteFiles;
  brokenAssets: BrokenAsset[];
  jsBytes: number;
  consoleErrors: ConsoleError[] | null;
  /** What the owner declared in vibeward.json, if anything. */
  intent?: VibewardIntent;
  /**
   * Check ids that do not apply to this site. Never evaluated, never reported as ok. Only
   * the keys matter here — the reason is the report's business, not the checker's.
   */
  notApplicable?: Map<string, unknown>;
}): Finding[] {
  const { pages, files, brokenAssets, jsBytes, consoleErrors, intent, notApplicable } = input;
  const findings: Finding[] = [];
  const origin = originOf(pages);
  const home = pages[0];
  const total = pages.length;

  const robots = analyzeRobots(files.robotsTxt);
  const blockedBots = robots.bots;

  // Declaring `aiCrawlers: "blocked"` does not silence the robots check, it inverts it: the
  // question stops being "are you shut out?" and becomes "are you shut out as thoroughly as
  // you think?". Believing you block AI while nine of twelve crawlers walk straight in is a
  // worse position than not having decided at all.
  if (intent?.aiCrawlers === 'blocked') {
    const open = AI_BOTS.filter((b) => !blockedBots.includes(b));
    if (open.length > 0) {
      findings.push({
        id: 'web_ai_block_incomplete',
        es: {
          label: 'Los rastreadores de IA no están bloqueados tan a fondo como se declaró',
          evidence: `vibeward.json declara \`intent.aiCrawlers: "blocked"\`, pero ${open.length} de los ${AI_BOTS.length} rastreadores de IA vigilados siguen permitidos: ${open.join(', ')}.`,
          impact:
            'Los rastreadores que quedaron fuera de la lista están leyendo y reutilizando el contenido, que es exactamente lo que el sitio quería evitar — y nadie se va a enterar, porque la intención se dejó por escrito y nunca se verificó.',
          why: `Un bloqueo parcial es lo peor de los dos mundos: ni la visibilidad de estar abierto, ni la protección de estar cerrado. Completarlo es un par \`User-agent\` / \`Disallow: /\` en \`public/robots.txt\` por cada agente que siga permitido. Conviene saberlo antes de confiar en ello: robots.txt es una petición, no un muro — a los rastreadores que deciden ignorarlo hay que pararlos en el CDN o en el servidor.`,
        },
        label: 'AI crawlers are not blocked as thoroughly as declared',
        severity: 'medium',
        kind: 'web',
        source: `${origin}/robots.txt`,
        evidence: `vibeward.json declares \`intent.aiCrawlers: "blocked"\`, but ${open.length} of ${AI_BOTS.length} watched AI crawlers are still allowed: ${open.join(', ')}.`,
        impact:
          'The content is being read and reused by the crawlers that were left out, which is exactly what the site set out to prevent — and nobody will notice, because the intention was recorded and never verified.',
        why: `A partial block is the worst of both worlds: none of the visibility of being open, none of the protection of being closed. Completing it means a \`User-agent\` / \`Disallow: /\` pair in \`public/robots.txt\` for each agent still allowed. Worth knowing before relying on it: robots.txt is a request, not a wall — crawlers that choose to ignore it have to be stopped at the CDN or the server.`,
        references: ['https://www.rfc-editor.org/rfc/rfc9309'],
        meta: { count: open.length },
      });
    }
  }

  if (blockedBots.length > 0) {
    const { viaWildcard, blockingAgents, managed } = robots;
    const where = blockingAgents.map((a) => `\`User-agent: ${a}\``).join(', ');
    const groups = blockingAgents.length === 1 ? 'that group' : 'those groups';

    // Where the rule actually lives decides what the reader is told to do, and getting it
    // wrong costs them the afternoon. Whoever edits a hand-written file must delete one
    // line, not the file: replacing robots.txt wholesale also deletes the Disallow rules the
    // owner does want (/admin, /checkout, staging) as a silent side effect of an SEO change.
    // Whoever is on a CDN that injects the block must not edit the file at all — their copy
    // is not the copy being served.
    const byHand = `It is undone by deleting only the \`Disallow: /\` line inside ${groups} — every other line in the file is doing a job and must stay.`;
    const byVendor = (m: NonNullable<RobotsVerdict['managed']>): string =>
      `${m.covers === 'all' ? "The rule is not written in the site's own `robots.txt`" : "Part of the rule is not written in the site's own `robots.txt`"}: it sits inside a block ${m.vendor} injects into the response, between its \`# BEGIN\` and \`# END\` markers. Editing the file in the repository changes nothing, because that is not the copy being served — it is switched off in ${m.where}.${m.covers === 'some' ? ` The remaining agents are declared outside the managed block and ${byHand.charAt(0).toLowerCase()}${byHand.slice(1)}` : ''}`;

    findings.push({
      id: 'web_robots_blocks_ai',
      label: 'robots.txt blocks AI crawlers',
      severity: 'high',
      kind: 'web',
      source: `${origin}/robots.txt`,
      evidence: `robots.txt carries an effective \`Disallow: /\` under ${where}, which shuts out ${blockedBots.length} AI crawler${blockedBots.length === 1 ? '' : 's'}: ${blockedBots.join(', ')}.${
        managed
          ? ` ${managed.covers === 'all' ? 'Every blocking group is' : 'Some of those groups are'} inside a \`${managed.vendor}\` managed block.`
          : ''
      }`,
      impact:
        'The site cannot be read by the assistants people now ask instead of Google, so it can never be cited, summarised or recommended in an AI answer. That referral channel is closed at the door.',
      why: `Blocking these agents removes the site from ChatGPT, Claude, Perplexity and Google AI answers. ${
        managed
          ? `It is rarely a decision — ${managed.vendor} switches this on for whole zones by default. `
          : 'It is one line in a text file, and it is usually there by copy-paste, not by decision. '
      }${managed ? byVendor(managed) : byHand}${
        viaWildcard
          ? ' If some paths really are meant to be private, name them (`Disallow: /admin`) instead of using a bare `/`.'
          : ' An empty `Disallow:` is equivalent to allowing everything.'
      }`,
      references: [
        'https://platform.openai.com/docs/bots',
        'https://www.rfc-editor.org/rfc/rfc9309',
      ],
      meta: { count: blockedBots.length },
      es: {
        label: 'robots.txt bloquea a los rastreadores de IA',
        evidence: `robots.txt aplica un \`Disallow: /\` efectivo bajo ${where}, que deja fuera a ${blockedBots.length} rastreador${blockedBots.length === 1 ? '' : 'es'} de IA: ${blockedBots.join(', ')}.${
          managed
            ? ` ${managed.covers === 'all' ? 'Todos esos grupos están' : 'Algunos de esos grupos están'} dentro de un bloque gestionado por \`${managed.vendor}\`.`
            : ''
        }`,
        impact:
          'El sitio no puede ser leído por los asistentes a los que la gente pregunta hoy en lugar de a Google, así que nunca podrá ser citado, resumido ni recomendado en una respuesta de IA. Ese canal de tráfico queda cerrado en la puerta.',
        why: `Bloquear a estos agentes saca al sitio de las respuestas de ChatGPT, Claude, Perplexity y Google AI. ${
          managed
            ? `Rara vez es una decisión: ${managed.vendor} lo activa por defecto en zonas enteras. ${
                managed.covers === 'all'
                  ? 'La regla no está escrita en el `robots.txt` del sitio'
                  : 'Parte de la regla no está escrita en el `robots.txt` del sitio'
              }: vive dentro de un bloque que ${managed.vendor} inyecta en la respuesta, entre sus marcadores \`# BEGIN\` y \`# END\`. Editar el fichero del repositorio no cambia nada, porque esa no es la copia que se está sirviendo — se desactiva en el panel de ${managed.vendor} de esta zona, en AI Crawl Control / el ajuste de robots.txt gestionado.${
                managed.covers === 'some'
                  ? ` Los agentes restantes sí están declarados fuera del bloque gestionado, y esos se arreglan borrando solo la línea \`Disallow: /\` de ${blockingAgents.length === 1 ? 'ese grupo' : 'esos grupos'}.`
                  : ''
              }`
            : `Es una línea en un fichero de texto, y casi siempre está ahí por copiar y pegar, no por decisión. Se deshace borrando solo la línea \`Disallow: /\` dentro de ${blockingAgents.length === 1 ? 'ese grupo' : 'esos grupos'} — el resto de líneas del fichero está haciendo su trabajo y debe quedarse.`
        }${
          viaWildcard
            ? ' Si de verdad hay rutas privadas, nómbralas (`Disallow: /admin`) en vez de usar un `/` a secas.'
            : ' Un `Disallow:` vacío equivale a permitirlo todo.'
        }`,
      },
    });
  }

  const emptyPages = pages.filter((p) => p.bodyTextLength < EMPTY_HTML_CHARS);
  if (home && home.bodyTextLength < EMPTY_HTML_CHARS) {
    findings.push({
      id: 'web_empty_html',
      es: {
        label: 'El HTML se sirve sin contenido',
        evidence: `La página de inicio devuelve ${home.bodyTextLength} caracteres de texto visible antes de que se ejecute JavaScript (${ofPagesEs(emptyPages.length, total)} por debajo de ${EMPTY_HTML_CHARS} caracteres).`,
        impact:
          'Para todo lo que no ejecuta JavaScript el sitio es una página en blanco: sin titular, sin texto, sin nada que indexar ni citar. La mayoría de rastreadores de IA no ejecutan scripts, así que para ellos el sitio sencillamente no existe.',
        why: 'Un shell renderizado en el cliente le entrega al rastreador un <div> vacío. Google renderiza tarde y de forma inconsistente; GPTBot, ClaudeBot y PerplexityBot no renderizan en absoluto. Cerrarlo es una decisión de arquitectura, no una edición de texto: o el titular y el primer párrafo reales viven dentro del nodo de montaje en `index.html` para estar en el fuente antes de que corra ningún script, o las páginas las genera un renderizador que emite HTML (Astro, React Server Components de Next.js, SSG de Vite).',
      },
      label: 'The HTML ships with no content',
      severity: 'high',
      kind: 'web',
      source: home.url,
      evidence: `The home page returns ${home.bodyTextLength} characters of visible text before JavaScript runs (${ofPages(emptyPages.length, total)} below ${EMPTY_HTML_CHARS} characters).`,
      impact:
        'To anything that does not run JavaScript the site is a blank page: no headline, no copy, nothing to index or quote. Most AI crawlers never execute scripts, so the site simply does not exist for them.',
      why: 'A client-rendered shell hands crawlers an empty <div>. Google renders eventually and inconsistently; GPTBot, ClaudeBot and PerplexityBot do not render at all. Closing it is an architecture decision, not a text edit: either the real headline and first paragraph live inside the mount node in `index.html` so they are in the source before any script runs, or the pages are built by a renderer that emits HTML (Astro, Next.js server components, Vite SSG).',
      meta: { pages: urlsOf(emptyPages), count: emptyPages.length },
    });
  }

  if (brokenAssets.length > 0) {
    const listed = brokenAssets.slice(0, 10);
    findings.push({
      id: 'web_broken_assets',
      es: {
        label: 'Recursos referenciados por el sitio devuelven error',
        evidence: `${brokenAssets.length} fichero(s) referenciado(s) responden con 4xx/5xx — ${listed
          .map((a) => `${a.url} → ${a.status} (referenciado desde ${a.from})`)
          .join(' · ')}${
          brokenAssets.length > listed.length
            ? ` · …y ${brokenAssets.length - listed.length} más`
            : ''
        }`,
        impact:
          'El visitante ve imágenes que faltan, secciones sin estilo o una función que nunca carga — la forma más rápida de parecer abandonado y perder la venta en la primera pantalla.',
        why: 'La página apunta a ficheros que no están desplegados: una ruta que solo existe en local, un recurso renombrado o una imagen que el build nunca copió. Los recursos que se sirven desde la raíz tienen que vivir en `public/` (Vite, Next.js, Astro) o en `static/` (SvelteKit) para que el build los copie — si no, la referencia sobra.',
      },
      label: 'Assets referenced by the site return an error',
      severity: 'high',
      kind: 'web',
      // The full list is evidence, not remediation: it is what proves the finding, and it is
      // the part a reader cannot reconstruct on their own.
      evidence: `${brokenAssets.length} referenced ${brokenAssets.length === 1 ? 'file answers' : 'files answer'} with 4xx/5xx — ${listed
        .map((a) => `${a.url} → ${a.status} (referenced from ${a.from})`)
        .join(' · ')}${
        brokenAssets.length > listed.length
          ? ` · …and ${brokenAssets.length - listed.length} more`
          : ''
      }`,
      impact:
        'Visitors see missing images, unstyled sections or a feature that never loads — the fastest way to look abandoned and lose the sale on the first screen.',
      why: 'The page points at files that are not deployed: a path that only exists locally, a renamed asset, or an image the build never copied. Assets served from the site root have to live in `public/` (Vite, Next.js, Astro) or `static/` (SvelteKit) for the build to copy them — otherwise the reference has to go.',
      meta: { count: brokenAssets.length },
    });
  }

  if (consoleErrors !== null && consoleErrors.length > 0) {
    const listed = consoleErrors.slice(0, 5);
    findings.push({
      id: 'web_console_errors',
      es: {
        label: 'La página lanza errores de JavaScript en el navegador',
        evidence: `${consoleErrors.length} error(es) de consola al cargar — ${listed
          .map((e) => `[${e.type}] ${e.text.slice(0, 300)}`)
          .join(' · ')}${
          consoleErrors.length > listed.length
            ? ` · …y ${consoleErrors.length - listed.length} más`
            : ''
        }`,
        impact:
          'Algo de la página ya está roto para todos los visitantes — un formulario que no envía, una sección que no aparece. Lo que sea que el error interrumpe, el usuario nunca lo completa.',
        why: 'Una excepción no capturada detiene el resto de ese script. Los errores en la primera carga no son cosméticos: casi siempre significan que una función está muerta. Reproducirlos con las DevTools abiertas en la pestaña Console es lo que convierte el mensaje de arriba en la línea de código que falló.',
      },
      label: 'The page throws JavaScript errors in the browser',
      severity: 'high',
      kind: 'web',
      source: home?.url,
      // The error text is the evidence and the only lead a reader has, so it is quoted at the
      // length that keeps a stack-trace line readable rather than truncated to a teaser.
      evidence: `${consoleErrors.length} console error${consoleErrors.length === 1 ? '' : 's'} on load — ${listed
        .map((e) => `[${e.type}] ${e.text.slice(0, 300)}`)
        .join(' · ')}${
        consoleErrors.length > listed.length
          ? ` · …and ${consoleErrors.length - listed.length} more`
          : ''
      }`,
      impact:
        'Something on the page is already broken for every visitor — a form that never submits, a section that never appears. Whatever the error interrupts, the user never completes.',
      why: 'An uncaught exception stops the rest of that script. Errors on first load are not cosmetic: they usually mean a feature is dead. Reproducing them with DevTools open on the Console tab is what turns the message above into the line of code that threw.',
      meta: { count: consoleErrors.length },
    });
  }

  const firstTitle = home?.title ?? null;
  if (total >= 2 && firstTitle && pages.every((p) => p.title === firstTitle)) {
    findings.push({
      id: 'web_duplicate_titles',
      es: {
        label: 'Todas las páginas tienen el mismo <title>',
        evidence: `Las ${total} páginas rastreadas envían el mismo título: "${firstTitle}".`,
        impact:
          'Todas las páginas compiten por el mismo resultado de búsqueda y no gana ninguna. El título es la línea azul que la gente pulsa en Google y la etiqueta de cada pestaña y marcador compartido.',
        why: 'Los buscadores tratan los títulos idénticos como páginas duplicadas: eligen una y descartan el resto. La causa habitual es un router de SPA que nunca actualiza el título. Cada página necesita su propio `<title>` de unos 50-60 caracteres, con el asunto de la página delante y la marca al final ("Precios — Acme"); en una SPA de React sin meta-framework eso significa fijar `document.title` en cada ruta.',
      },
      label: 'Every page has the same <title>',
      severity: 'high',
      kind: 'web',
      evidence: `All ${total} crawled pages send the same title: "${firstTitle}".`,
      impact:
        'Every page competes for the same search result and none of them wins. The title is the blue line people click in Google and the label of every shared tab and bookmark.',
      why: 'Search engines treat identical titles as duplicate pages and pick one, dropping the rest. A one-page-app router that never updates the title is the usual cause. Each page needs its own `<title>` of roughly 50-60 characters, page subject first and brand last ("Pricing — Acme"); in a React SPA with no meta framework that means setting `document.title` per route.',
      meta: { pages: urlsOf(pages), count: total },
    });
  }

  const noTitle = pages.filter((p) => !p.title);
  if (home && !home.title) {
    findings.push({
      id: 'web_missing_title',
      es: {
        label: 'La página de inicio no tiene <title>',
        evidence: `${ofPagesEs(noTitle.length, total)} no tienen etiqueta <title>, incluida la página de inicio.`,
        impact:
          'Google imprime la URL o una frase inventada como titular del resultado de búsqueda, y la pestaña del navegador muestra el dominio pelado. Es el texto más visible que posee el sitio.',
        why: 'El <title> es el titular de cada resultado de búsqueda, de cada enlace compartido y de cada marcador. Sin él no hay nada que pulsar. Cada página necesita uno en su `<head>`, diciendo a qué se dedica el negocio en vez de repetir solo la marca.',
      },
      label: 'The home page has no <title>',
      severity: 'high',
      kind: 'web',
      source: home.url,
      evidence: `${ofPages(noTitle.length, total)} have no <title> tag, including the home page.`,
      impact:
        'Google prints the URL or an invented phrase as the search result headline, and the browser tab reads as the bare domain. It is the single most visible piece of text the site owns.',
      why: 'The <title> is the headline of every search result, every shared link and every bookmark. Without it there is nothing to click. Every page needs one in its `<head>`, naming what the business does rather than repeating the brand alone.',
      meta: { pages: urlsOf(noTitle), count: noTitle.length },
    });
  }

  const noDescription = pages.filter((p) => !p.metaDescription);
  if (noDescription.length > 0) {
    findings.push({
      id: 'web_missing_meta_description',
      es: {
        label: 'Hay páginas sin meta description',
        evidence: `${ofPagesEs(noDescription.length, total)} no tienen <meta name="description">.`,
        impact:
          'Google rellena las dos líneas de debajo del enlace con el texto que rasque de la página, así que el argumento que lee un visitante antes de decidir si pulsa lo escribe un algoritmo en lugar del dueño.',
        why: 'La description es el texto publicitario del resultado de búsqueda. No cambia el posicionamiento, cambia el porcentaje de clics. Una por página, de 150-160 caracteres, escrita para una persona que está decidiendo si pulsa — una genérica es peor que ninguna, porque parece escrita y así nadie escribe nunca la de verdad.',
      },
      label: 'Pages have no meta description',
      severity: 'medium',
      kind: 'web',
      evidence: `${ofPages(noDescription.length, total)} have no <meta name="description">.`,
      impact:
        'Google fills the two lines under the link with whatever text it scrapes off the page, so the pitch a visitor reads before deciding to click is written by an algorithm instead of by the owner.',
      why: 'The description is the ad copy of the search result. It does not change ranking, it changes the click-through rate. One per page, 150-160 characters, written for a human deciding whether to click — a generic one is worse than none, because it looks written and so nobody ever writes the real one.',
      meta: { pages: urlsOf(noDescription), count: noDescription.length },
    });
  }

  const noOg = pages.filter((p) => !p.ogTitle || !p.ogImage);
  if (noOg.length > 0) {
    findings.push({
      id: 'web_missing_og',
      es: {
        label: 'Hay páginas sin etiquetas Open Graph',
        evidence: `A ${ofPagesEs(noOg.length, total)} les falta og:title u og:image.`,
        impact:
          'Compartido por WhatsApp, LinkedIn, Slack o X, el enlace aparece como una URL pelada sin imagen ni título, y la gente pasa de largo. Cada vez que alguien comparte el sitio, se desperdicia.',
        why: 'Las etiquetas Open Graph son lo que leen las redes sociales y las apps de mensajería para construir la tarjeta de vista previa. Sin ellas no hay tarjeta. El juego completo en el `<head>` de cada página es og:title, og:description, og:image, og:url y og:type, más `twitter:card` en `summary_large_image` — y og:image tiene que ser una imagen real de 1200x630, porque si falta se renderiza un recuadro en blanco en lugar de ninguna tarjeta.',
      },
      label: 'Pages have no Open Graph tags',
      severity: 'medium',
      kind: 'web',
      evidence: `${ofPages(noOg.length, total)} are missing og:title or og:image.`,
      impact:
        'Shared on WhatsApp, LinkedIn, Slack or X the link renders as a naked URL with no image and no title, which people scroll past. Every share the site gets is wasted.',
      why: "Open Graph tags are what social platforms and chat apps read to build the preview card. Without them there is no card. A complete set in each page's `<head>` is og:title, og:description, og:image, og:url and og:type, plus `twitter:card` set to `summary_large_image` — and og:image has to be a real 1200x630 image, since a missing one renders as a blank box rather than no card at all.",
      references: ['https://ogp.me/'],
      meta: { pages: urlsOf(noOg), count: noOg.length },
    });
  }

  const noCanonical = pages.filter((p) => !p.canonical);
  if (noCanonical.length > 0) {
    findings.push({
      id: 'web_missing_canonical',
      es: {
        label: 'Hay páginas que no declaran URL canónica',
        evidence: `${ofPagesEs(noCanonical.length, total)} no tienen <link rel="canonical">.`,
        impact:
          'La misma página accesible con y sin www, con y sin barra final, o con un parámetro de campaña, cuenta como varias páginas que compiten entre sí, y reparte entre ellas la autoridad que el sitio se ha ganado.',
        why: `La etiqueta canonical nombra la única dirección real de una página para que los duplicados se consoliden en ella en vez de competir con ella. Cada página necesita su propio \`<link rel="canonical">\` apuntando a su propia URL absoluta (\`${origin}/precios\` en la página de precios) — apuntar todas las páginas a la de inicio es el error habitual, y le dice a los buscadores que el resto del sitio no existe.`,
      },
      label: 'Pages declare no canonical URL',
      severity: 'medium',
      kind: 'web',
      evidence: `${ofPages(noCanonical.length, total)} have no <link rel="canonical">.`,
      impact:
        'The same page reachable at www and non-www, with and without a trailing slash, or with a campaign parameter, is counted as several competing pages, splitting whatever authority the site has earned.',
      why: `The canonical tag names the one real address of a page so duplicates consolidate into it instead of competing with it. Each page needs its own \`<link rel="canonical">\` pointing at its own absolute URL (\`${origin}/pricing\` on the pricing page) — pointing every page at the home page is the common mistake, and it tells search engines the rest of the site does not exist.`,
      references: [
        'https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls',
      ],
      meta: { pages: urlsOf(noCanonical), count: noCanonical.length },
    });
  }

  const noJsonLd = pages.filter((p) => p.jsonLdBlocks === 0);
  if (noJsonLd.length > 0) {
    findings.push({
      id: 'web_missing_structured_data',
      es: {
        label: 'Sin datos estructurados (JSON-LD)',
        evidence: `${ofPagesEs(noJsonLd.length, total)} no contienen ningún bloque <script type="application/ld+json">.`,
        impact:
          'Los buscadores y los asistentes tienen que adivinar qué es el negocio, qué vende y dónde está. Los resultados enriquecidos (valoraciones, precios, FAQ, horarios) no están disponibles para un sitio que nunca los declara.',
        why: 'Los datos estructurados son la versión legible por máquina de la página. Es como un asistente responde "quiénes son y qué hacen" con datos en vez de con suposiciones. Lo mínimo es un bloque `application/ld+json` en el `<head>` de la página de inicio declarando una `Organization` con el nombre real, url, logo, description y los enlaces `sameAs` a los perfiles — los valores tienen que ser ciertos, porque esto es el texto que un asistente repite tal cual.',
      },
      label: 'No structured data (JSON-LD)',
      severity: 'medium',
      kind: 'web',
      evidence: `${ofPages(noJsonLd.length, total)} contain no <script type="application/ld+json"> block.`,
      impact:
        'Search engines and assistants have to guess what the business is, what it sells and where it is. Rich results (ratings, prices, FAQ, opening hours) are not available to a site that never declares them.',
      why: 'Structured data is the machine-readable version of the page. It is how an assistant answers "who are they and what do they do" with facts instead of guesses. The minimum is one `application/ld+json` block in the home page `<head>` declaring an `Organization` with the real name, url, logo, description and `sameAs` profile links — the values have to be true, because this is the copy an assistant repeats verbatim.',
      references: ['https://schema.org/Organization'],
      meta: { pages: urlsOf(noJsonLd), count: noJsonLd.length },
    });
  }

  const noH1 = pages.filter((p) => p.h1Count === 0);
  const manyH1 = pages.filter((p) => p.h1Count > 1);
  if (noH1.length > 0 || manyH1.length > 0) {
    const parts: string[] = [];
    const partsEs: string[] = [];
    if (noH1.length > 0) {
      parts.push(`${ofPages(noH1.length, total)} have no <h1>`);
      partsEs.push(`${ofPagesEs(noH1.length, total)} no tienen <h1>`);
    }
    if (manyH1.length > 0) {
      const most = Math.max(...manyH1.map((p) => p.h1Count));
      parts.push(`${ofPages(manyH1.length, total)} have more than one (up to ${most})`);
      partsEs.push(`${ofPagesEs(manyH1.length, total)} tienen más de uno (hasta ${most})`);
    }
    findings.push({
      id: 'web_h1_structure',
      es: {
        label: 'La estructura de encabezados está mal',
        evidence: `${partsEs.join('; ')}.`,
        impact:
          'La única línea que le dice a un buscador, a un asistente y a un lector de pantalla de qué va la página falta o está repetida, así que la página queda archivada bajo el asunto equivocado o bajo ninguno.',
        why: 'Exactamente un <h1> por página, con el asunto de esa página. Los de más suelen ser decisiones de estilo, no encabezados — se bajan a <h2> conservando el aspecto en una clase, en vez de borrarlos.',
      },
      label: 'Heading structure is wrong',
      severity: 'medium',
      kind: 'web',
      evidence: `${parts.join('; ')}.`,
      impact:
        'The one line that tells a search engine, an assistant and a screen reader what the page is about is missing or repeated, so the page is filed under the wrong subject or under none.',
      why: 'Exactly one <h1> per page, carrying the subject of that page. Extra ones are usually styling choices, not headings — they get demoted to <h2> with the look kept in a class, rather than deleted.',
      meta: { pages: [...urlsOf(noH1), ...urlsOf(manyH1)], count: noH1.length + manyH1.length },
    });
  }

  if (!files.sitemapXml) {
    findings.push({
      id: 'web_missing_sitemap',
      es: {
        label: 'Sin sitemap.xml',
        evidence: `${origin}/sitemap.xml no se sirve.`,
        impact:
          'Las páginas que no están enlazadas desde la de inicio pueden pasar semanas sin que nadie las vea, o no indexarse nunca, y cada actualización tarda más en aparecer en las búsquedas.',
        why: `Un sitemap es la lista de páginas que el dueño quiere que se indexen. Sin él, los rastreadores solo encuentran lo que se van topando. Es un \`urlset\` de entradas \`<loc>\` en \`public/sitemap.xml\` (\`static/sitemap.xml\` en SvelteKit), con una línea \`Sitemap: ${origin}/sitemap.xml\` en robots.txt que apunte a él${total > 0 ? ` — este escaneo alcanzó ${total} página${total === 1 ? '' : 's'}, listadas en "Páginas escaneadas"` : ''}.`,
      },
      label: 'No sitemap.xml',
      severity: 'medium',
      kind: 'web',
      source: `${origin}/sitemap.xml`,
      evidence: `${origin}/sitemap.xml is not served.`,
      impact:
        'Pages that are not linked from the home page can go unnoticed for weeks or never get indexed at all, and every update takes longer to show up in search.',
      why: `A sitemap is the list of pages the owner wants indexed. Without it crawlers only find what they happen to stumble on. It is a \`urlset\` of \`<loc>\` entries at \`public/sitemap.xml\` (\`static/sitemap.xml\` on SvelteKit), with a \`Sitemap: ${origin}/sitemap.xml\` line in robots.txt pointing at it${total > 0 ? ` — this scan reached ${total} page${total === 1 ? '' : 's'}, listed under "Pages scanned"` : ''}.`,
      references: ['https://www.sitemaps.org/protocol.html'],
    });
  }

  if (!files.llmsTxt) {
    findings.push({
      id: 'web_missing_llms_txt',
      es: {
        label: 'Sin llms.txt',
        evidence: `${origin}/llms.txt no se sirve.`,
        impact:
          'Cuando a un asistente le preguntan por este negocio, tiene que reconstruir la oferta con el marcado que consiga interpretar. Un fichero corto y bien escrito es la diferencia entre que lo describan bien y que lo describan mal.',
        why: 'llms.txt es el resumen en texto plano que una IA lee primero: qué es el sitio, para quién es y qué páginas importan. Vive en `public/llms.txt` — un H1 con el nombre, una cita con una frase sobre la oferta y el público, y una lista `## Pages` con las páginas que merece la pena leer y una línea por cada una. Solo funciona si dice lo que el negocio vende de verdad; una versión de relleno es peor que ninguna, porque se lee como si fuera autoritativa.',
      },
      label: 'No llms.txt',
      severity: 'medium',
      kind: 'web',
      source: `${origin}/llms.txt`,
      evidence: `${origin}/llms.txt is not served.`,
      impact:
        'When an assistant is asked about this business it has to reconstruct the offer from whatever markup it can parse. A short curated file is the difference between being described accurately and being described wrong.',
      why: 'llms.txt is the plain-text summary an AI reads first: what the site is, who it is for, and which pages matter. It lives at `public/llms.txt` — an H1 with the name, a blockquote with one sentence on the offer and the audience, and a `## Pages` list of the pages worth reading with a line each. It only works if it says what the business actually sells; a placeholder version is worse than none, because it reads as authoritative.',
      references: ['https://llmstxt.org/'],
    });
  }

  const noLang = pages.filter((p) => !p.lang);
  if (noLang.length > 0) {
    findings.push({
      id: 'web_missing_lang',
      es: {
        label: 'La etiqueta <html> no declara idioma',
        evidence: `${ofPagesEs(noLang.length, total)} no tienen el atributo lang en <html>.`,
        impact:
          'Los navegadores ofrecen traducir una página que ya está en el idioma del visitante, los lectores de pantalla eligen la voz equivocada y los buscadores pueden servir el sitio al país que no toca.',
        why: 'Un atributo — `lang` en `<html>` — le dice a cualquier cliente en qué idioma está escrito el contenido. Las plantillas vienen con él vacío o copiado del starter, así que hay que ponerlo en el idioma en el que está el texto de verdad, no en el que traía la plantilla.',
      },
      label: 'The <html> tag declares no language',
      severity: 'medium',
      kind: 'web',
      evidence: `${ofPages(noLang.length, total)} have no lang attribute on <html>.`,
      impact:
        'Browsers offer to translate a page that is already in the language of the visitor, screen readers pick the wrong voice, and search engines can serve the site to the wrong country.',
      why: 'One attribute — `lang` on `<html>` — tells every client what language the content is written in. Templates ship with it empty or copied from the starter, so it has to be set to the language the copy is actually in, not the one the template came with.',
      meta: { pages: urlsOf(noLang), count: noLang.length },
    });
  }

  const imgTotal = pages.reduce((n, p) => n + p.imgTotal, 0);
  const imgWithoutAlt = pages.reduce((n, p) => n + p.imgWithoutAlt, 0);
  if (imgTotal > 0 && imgWithoutAlt > 0) {
    const affected = pages.filter((p) => p.imgWithoutAlt > 0);
    findings.push({
      id: 'web_missing_alt',
      es: {
        label: 'Hay imágenes sin texto alternativo',
        evidence: `${imgWithoutAlt} de ${imgTotal} imágenes no tienen atributo alt, repartidas en ${ofPagesEs(affected.length, total)}.`,
        impact:
          'Los visitantes ciegos oyen "imagen" en lugar del producto, la búsqueda de imágenes no devuelve nunca estas fotos y, en varias jurisdicciones, es una obligación de accesibilidad y no un detalle.',
        why: 'El texto alt es lo que una imagen le dice a quien —o a lo que— no puede verla: lectores de pantalla, búsqueda de imágenes y cualquier rastreador que indexe la página. Tiene que describir lo que la foto muestra de verdad, en el idioma de la página — lo que significa mirar cada imagen, no generar texto a partir del nombre del fichero. Las imágenes puramente decorativas llevan un `alt=""` vacío, que no es lo mismo que no llevar ninguno.',
      },
      label: 'Images have no alt text',
      severity: 'medium',
      kind: 'web',
      evidence: `${imgWithoutAlt} of ${imgTotal} images have no alt attribute, across ${ofPages(affected.length, total)}.`,
      impact:
        'Blind visitors hear "image" instead of the product, image search never returns these pictures, and in several jurisdictions it is an accessibility obligation rather than a nicety.',
      why: 'Alt text is what an image says to anyone or anything that cannot see it: screen readers, image search, and any crawler indexing the page. It has to describe what the picture actually shows, in the page\'s language — which means looking at each image, not generating text from the filename. Purely decorative images take an empty `alt=""`, which is different from having none.',
      meta: { pages: urlsOf(affected), count: imgWithoutAlt },
    });
  }

  const probe = files.notFound;
  if (probe.status > 0 && (probe.status < 400 || !probe.distinct)) {
    findings.push({
      id: 'web_missing_404',
      es: {
        label: 'Las URLs inexistentes no devuelven un 404 real',
        evidence:
          probe.status < 400
            ? `Una URL que no existe respondió ${probe.status} en lugar de 404${probe.distinct ? '' : ' y sirvió la página de inicio'}.`
            : `El cuerpo de la respuesta 404 es la misma página que la de inicio.`,
        impact:
          'Los buscadores indexan infinitas URLs inexistentes como copias de la página de inicio, y quien se equivoque al teclear un enlace aterriza en algo que parece correcto pero no es la página que buscaba.',
        why: 'Una SPA que sirve index.html para cualquier ruta nunca le dice a nadie que una URL está mal. La señal es el código de estado, no el diseño — una página que dice "no encontrado" mientras responde 200 no cuenta. Los hostings estáticos leen `public/404.html`, Next.js usa `app/not-found.tsx`, y una SPA de React necesita una ruta catch-all.',
      },
      label: 'Unknown URLs do not return a real 404',
      severity: 'low',
      kind: 'web',
      source: `${origin}/vibeward-404-probe`,
      evidence:
        probe.status < 400
          ? `A URL that does not exist answered ${probe.status} instead of 404${probe.distinct ? '' : ' and served the home page'}.`
          : `The 404 response body is the same page as the home page.`,
      impact:
        'Search engines index infinite non-existent URLs as copies of the home page, and a visitor who mistypes a link lands on something that looks fine but is not the page they wanted.',
      why: 'A single-page app that serves index.html for every path never tells anyone that a URL is wrong. The status code is the signal, not the design — a page that says "not found" while answering 200 does not count. Static hosts read `public/404.html`, Next.js uses `app/not-found.tsx`, and a React SPA needs a catch-all route.',
    });
  }

  if (!files.faviconOk && !pages.some((p) => p.faviconLink)) {
    findings.push({
      id: 'web_missing_favicon',
      es: {
        label: 'Sin favicon',
        evidence:
          'No se sirve ningún favicon ni se declara <link rel="icon"> en ninguna página rastreada.',
        impact:
          'La pestaña, el marcador y la pantalla de inicio del móvil muestran una hoja en blanco. Es pequeño, es gratis de arreglar, y es la diferencia entre un negocio y una demo de fin de semana.',
        why: 'El favicon es la única marca que le queda a un sitio en una fila de treinta pestañas abiertas. Necesita un `public/favicon.svg` más un `public/apple-touch-icon.png` de 180x180 para la pantalla de inicio del móvil, ambos referenciados con `<link rel="icon">` y `<link rel="apple-touch-icon">` en el `<head>`.',
      },
      label: 'No favicon',
      severity: 'low',
      kind: 'web',
      source: `${origin}/favicon.ico`,
      evidence: 'No favicon is served and no <link rel="icon"> is declared on any crawled page.',
      impact:
        'The tab, the bookmark and the phone home screen show a blank sheet of paper. It is small, it is free to fix, and it is the difference between a business and a weekend demo.',
      why: 'The favicon is the only branding a site gets in a row of thirty open tabs. It needs a `public/favicon.svg` plus a 180x180 `public/apple-touch-icon.png` for phone home screens, both referenced with `<link rel="icon">` and `<link rel="apple-touch-icon">` in the `<head>`.',
    });
  }

  // External bundles plus the biggest inline-script document. Inline script is counted because
  // it is downloaded and parsed exactly like a bundle — a 3 MB `<script>` written into the HTML
  // was sailing past a check named "JavaScript payload is heavy" purely because it had no `src`.
  const inlineMax = Math.max(0, ...pages.map((p) => p.inlineScriptBytes));
  const inlinePage = pages.find((p) => p.inlineScriptBytes === inlineMax);
  const totalJs = jsBytes + inlineMax;
  if (totalJs > HEAVY_BUNDLE_BYTES) {
    const heavyInline = inlineMax > HEAVY_BUNDLE_BYTES / 2;
    const inlineNote = heavyInline
      ? ` ${formatBytes(inlineMax)} of that is inline \`<script>\` written straight into the HTML document, which cannot be cached and blocks the parser until it fully downloads.`
      : '';
    const inlineNoteEs = heavyInline
      ? ` ${formatBytes(inlineMax)} de eso es \`<script>\` en línea escrito directamente en el documento HTML, que no se puede cachear y bloquea el parser hasta que se descarga entero.`
      : '';
    findings.push({
      id: 'web_heavy_bundle',
      es: {
        label: 'La carga de JavaScript es pesada',
        evidence: `Se descargan ${formatBytes(totalJs)} de JavaScript sin comprimir para renderizar la página (umbral: 1.0 MB).${inlineNoteEs}`,
        impact:
          'En un móvil de gama media con datos móviles la página se queda en blanco varios segundos, y una parte importante de los visitantes se va antes de que pinte — nunca llegan a ver la oferta.',
        why: `Todo lo que bloquea el primer render — bundles externos y script en línea por igual — retrasa la página por código al que el visitante quizá no llegue nunca. Qué parte tiene la culpa es una medición, no una suposición: \`vite-bundle-visualizer\` o \`source-map-explorer\` te dicen qué bundle es, y ${heavyInline ? 'un script en línea de varios megas suele ser datos o plantillas que deberían ir en un fichero aparte cacheable o en una respuesta del servidor' : 'lo habitual es cargar de forma diferida todo lo que no hace falta para el primer pintado'}.`,
      },
      label: 'JavaScript payload is heavy',
      severity: 'low',
      kind: 'web',
      evidence: `${formatBytes(totalJs)} of uncompressed JavaScript is downloaded to render the page (threshold: 1.0 MB).${inlineNote}`,
      impact:
        'On a mid-range phone over mobile data the page stays blank for seconds, and a large share of visitors leave before it paints — they never see the offer at all.',
      why: `Everything that blocks the first render — external bundles and inline script alike — delays the page for code the visitor may never reach. Which part is responsible is a measurement, not a guess: \`vite-bundle-visualizer\` or \`source-map-explorer\` name a bundle, and ${inlineMax > HEAVY_BUNDLE_BYTES / 2 ? 'a multi-megabyte inline script usually means data or templates that belong in a separate cached file or a server response' : 'the usual fix is lazy-loading whatever is not needed for the first paint'}.`,
      meta: {
        count: totalJs,
        pages: inlineMax > 0 && inlinePage ? [inlinePage.url] : undefined,
      },
    });
  }

  // Filtered at the end rather than guarded at every push: one place to look, and a new
  // check can never forget to honour the config.
  return notApplicable ? findings.filter((f) => !notApplicable.has(f.id)) : findings;
}
