import type { Finding, VibewardIntent } from '../core/types.js';
import type { SiteFiles, BrokenAsset } from '../http/crawl.js';
import type { ConsoleError } from './console.js';

// Website quality & AI-visibility checks. Everything here is pure: the network layer
// hands over the crawled HTML and this module only measures absences — the tag that is
// not there, the file that was never generated. That is exactly what a site generated by
// an AI and published untouched looks like.

/** Window for the <head> signals (title, meta, link, lang, JSON-LD). They live up front. */
const MAX_HTML = 200 * 1024;

/** Window for the body signals (<h1>, <img>, visible text). A guard against OOM, not a scan limit. */
const MAX_DOC = 5 * 1024 * 1024;

/** A page with less visible text than this is an empty shell, not a page. */
const EMPTY_HTML_CHARS = 200;

/** Uncompressed JS above this is a slow first paint on a phone. */
const HEAVY_BUNDLE_BYTES = 1_048_576;

/** Signals evaluated by `fingerprintStack`. Fixed so the score reads the same everywhere. */
const FINGERPRINT_TOTAL = 12;

/** Free hosting subdomains — nobody ships a real business on one on purpose. */
const PLATFORM_DOMAINS = [
  'vercel.app',
  'netlify.app',
  'lovable.app',
  'bolt.new',
  'pages.dev',
  'github.io',
  'web.app',
  'firebaseapp.com',
  'replit.app',
  'onrender.com',
  'surge.sh',
];

/** The crawlers that decide whether a site can be quoted inside an AI answer. */
const AI_BOTS = [
  'GPTBot',
  'OAI-SearchBot',
  'ChatGPT-User',
  'ClaudeBot',
  'anthropic-ai',
  'Claude-Web',
  'PerplexityBot',
  'CCBot',
  'Google-Extended',
  'Applebot-Extended',
  'Bytespider',
  'meta-externalagent',
];

export interface PageSignals {
  url: string;
  title: string | null;
  metaDescription: string | null;
  canonical: string | null;
  ogTitle: string | null;
  ogImage: string | null;
  lang: string | null;
  h1Count: number;
  jsonLdBlocks: number;
  imgTotal: number;
  imgWithoutAlt: number;
  faviconLink: boolean;
  bodyTextLength: number;
}

export interface StackFingerprint {
  host: string;
  platformDomain: string | null;
  framework: string | null;
  clientRendered: boolean;
  signals: string[];
  score: number;
  total: number;
}

// ---------------------------------------------------------------------------
// HTML parsing — regex on purpose. Bundler output is predictable markup and a
// real parser would be a dependency for no extra signal.
// ---------------------------------------------------------------------------

function clean(value: string | null | undefined): string | null {
  if (value === null || value === undefined) return null;
  const text = value.replace(/\s+/g, ' ').trim();
  return text.length > 0 ? text : null;
}

/** All opening tags of one element, as raw strings, so attributes can be read off them. */
function tagsOf(html: string, name: string): string[] {
  return html.match(new RegExp(`<${name}\\b[^>]*>`, 'gi')) ?? [];
}

function attr(tag: string, name: string): string | null {
  const m = tag.match(new RegExp(`\\b${name}\\s*=\\s*("([^"]*)"|'([^']*)'|([^\\s"'>]+))`, 'i'));
  if (!m) return null;
  return m[2] ?? m[3] ?? m[4] ?? '';
}

function stripComments(html: string): string {
  return html.replace(/<!--[\s\S]*?-->/g, ' ');
}

/**
 * Drops script, style and noscript bodies. Anything counted from the page body has to run
 * on this: a React bundle inlined in the page is full of `<h1>` and `<img>` inside strings,
 * and counting those turns "this page has no heading" into a lie about a client's site.
 */
function stripInert(html: string): string {
  return html.replace(/<(script|style|noscript)\b[^>]*>[\s\S]*?<\/\1>/gi, ' ');
}

/** Visible text: comments, script/style/noscript bodies and every tag removed. */
function visibleTextLength(html: string): number {
  return stripInert(stripComments(html))
    .replace(/<[^>]+>/g, ' ')
    .replace(/\s+/g, ' ')
    .trim().length;
}

export function parsePage(html: string, url: string): PageSignals {
  // Comments go first: markup left commented out is not markup, and starter templates
  // are full of commented-out meta tags.
  //
  // Two windows, on purpose. `doc` is the cheap one for everything that lives in <head>.
  // Body signals get `full`, because a Next.js RSC payload or an inline critical-CSS block
  // routinely pushes the real <h1> past 200 KB — and reading a page as heading-less because
  // the scanner stopped early is a false accusation in a report someone paid for.
  const full = stripComments(html.slice(0, MAX_DOC));
  const doc = full.slice(0, MAX_HTML);
  const visible = stripInert(full);

  let metaDescription: string | null = null;
  let ogTitle: string | null = null;
  let ogImage: string | null = null;
  for (const tag of tagsOf(doc, 'meta')) {
    const key = (attr(tag, 'name') ?? attr(tag, 'property') ?? '').toLowerCase();
    const content = clean(attr(tag, 'content'));
    if (!key || !content) continue;
    if (key === 'description') metaDescription ??= content;
    else if (key === 'og:title') ogTitle ??= content;
    else if (key === 'og:image') ogImage ??= content;
  }

  let canonical: string | null = null;
  let faviconLink = false;
  for (const tag of tagsOf(doc, 'link')) {
    const rels = (attr(tag, 'rel') ?? '').toLowerCase().split(/\s+/);
    if (rels.includes('canonical')) canonical ??= clean(attr(tag, 'href'));
    if (rels.includes('icon') || rels.includes('apple-touch-icon') || rels.includes('mask-icon')) {
      faviconLink = true;
    }
  }

  const images = tagsOf(visible, 'img');

  return {
    url,
    title: clean(doc.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]),
    metaDescription,
    canonical,
    ogTitle,
    ogImage,
    lang: clean(attr(doc.match(/<html\b[^>]*>/i)?.[0] ?? '', 'lang')),
    h1Count: (visible.match(/<h1(?:\s[^>]*)?>/gi) ?? []).length,
    // Read off `doc` and not `visible`: this is the one signal carried BY a <script> tag.
    jsonLdBlocks: tagsOf(doc, 'script').filter((t) =>
      (attr(t, 'type') ?? '').toLowerCase().includes('ld+json'),
    ).length,
    imgTotal: images.length,
    // `alt=""` is the deliberate "decorative image" marker, so only a missing attribute counts.
    imgWithoutAlt: images.filter((t) => attr(t, 'alt') === null).length,
    faviconLink,
    bodyTextLength: visibleTextLength(full),
  };
}

// ---------------------------------------------------------------------------
// Stack fingerprint
// ---------------------------------------------------------------------------

function hostOf(url: string): string {
  try {
    return new URL(url).hostname;
  } catch {
    return url;
  }
}

function detectFramework(html: string): string | null {
  if (/\/_next\//.test(html)) return 'Next.js';
  if (/__NUXT__|\/_nuxt\//.test(html)) return 'Nuxt';
  if (/__sveltekit|\/_app\/immutable\//i.test(html)) return 'SvelteKit';
  if (/___gatsby|\/page-data\/|gatsby-chunk-mapping/i.test(html)) return 'Gatsby';
  if (/astro-island|data-astro/i.test(html)) return 'Astro';
  if (/\/static\/js\/main\.[0-9a-f]{6,}\.js/i.test(html)) return 'Create React App';

  const viteEntry = /\/assets\/index-[A-Za-z0-9_-]{6,}\.js/.test(html);
  const moduleScript = tagsOf(html, 'script').some(
    (t) => /module/i.test(attr(t, 'type') ?? '') && /\bcrossorigin\b/i.test(t),
  );
  if (viteEntry || moduleScript) {
    return /id=["']root["']|data-reactroot|__REACT_DEVTOOLS/.test(html) ? 'Vite + React' : 'Vite';
  }
  return null;
}

/**
 * Scores how much this looks like "generated by an AI and published without a second pass".
 * `files` is optional because two of the twelve signals (sitemap.xml, llms.txt) cannot be
 * seen in the HTML; when it is absent those two are simply never counted against the site —
 * an undercount is honest, guessing them from markup would not be.
 */
export function fingerprintStack(
  homeHtml: string,
  homeUrl: string,
  jsBytes: number,
  files: SiteFiles | null = null,
): StackFingerprint {
  // parsePage gets the whole document and picks its own windows; pre-truncating here would
  // hand it a body that stops at 200 KB and make `clientRendered` fire on a full page.
  const page = parsePage(homeHtml, homeUrl);
  const doc = stripComments(homeHtml.slice(0, MAX_HTML));
  const host = hostOf(homeUrl);
  const platformDomain = PLATFORM_DOMAINS.find((d) => host === d || host.endsWith(`.${d}`)) ?? null;
  const hasScriptSrc = tagsOf(doc, 'script').some((t) => attr(t, 'src') !== null);
  const clientRendered = page.bodyTextLength < EMPTY_HTML_CHARS && hasScriptSrc;

  const signals: string[] = [];
  if (platformDomain) signals.push(`Still on the default *.${platformDomain} domain`);
  if (clientRendered) signals.push('HTML carries no content — JavaScript renders everything');
  if (!page.title) signals.push('No <title>');
  if (!page.metaDescription) signals.push('No meta description');
  if (!page.ogTitle && !page.ogImage) signals.push('No Open Graph tags');
  if (!page.canonical) signals.push('No canonical URL');
  if (page.jsonLdBlocks === 0) signals.push('No structured data');
  if (files && !files.sitemapXml) signals.push('No sitemap.xml');
  if (!page.faviconLink && !(files?.faviconOk ?? false)) signals.push('No favicon');
  if (!page.lang) signals.push('No lang on <html>');
  if (files && !files.llmsTxt) signals.push('No llms.txt');
  if (jsBytes > HEAVY_BUNDLE_BYTES) signals.push(`JavaScript over 1 MB (${formatBytes(jsBytes)})`);

  return {
    host,
    platformDomain,
    framework: detectFramework(doc),
    clientRendered,
    signals,
    score: signals.length,
    total: FINGERPRINT_TOTAL,
  };
}

// ---------------------------------------------------------------------------
// robots.txt
// ---------------------------------------------------------------------------

interface RobotsRule {
  allow: boolean;
  path: string;
}

interface RobotsGroup {
  agents: string[];
  rules: RobotsRule[];
}

/**
 * Groups the file the way a crawler does: consecutive `User-agent` lines share the rules
 * that follow, and the first rule line closes the agent list of that group.
 */
function parseRobots(text: string): RobotsGroup[] {
  const groups: RobotsGroup[] = [];
  let current: RobotsGroup | null = null;
  let takingAgents = false;

  for (const raw of text.split(/\r?\n/)) {
    const line = (raw.split('#')[0] ?? '').trim();
    if (!line) continue;
    const m = line.match(/^([A-Za-z-]+)\s*:\s*(.*)$/);
    if (!m) continue;
    const field = m[1]!.toLowerCase();
    const value = m[2]!.trim();

    if (field === 'user-agent') {
      if (!current || !takingAgents) {
        current = { agents: [], rules: [] };
        groups.push(current);
      }
      current.agents.push(value.toLowerCase());
      takingAgents = true;
    } else if (field === 'allow' || field === 'disallow') {
      if (current) current.rules.push({ allow: field === 'allow', path: value });
      takingAgents = false;
    } else if (field !== 'sitemap' && field !== 'host') {
      takingAgents = false; // crawl-delay & friends belong to the group but end its agent list
    }
  }
  return groups;
}

function blocksEverything(rules: RobotsRule[]): boolean {
  // `Disallow:` empty allows everything; `Disallow: /$` only hides the home page.
  const disallowsRoot = rules.some((r) => !r.allow && /^\/\**$/.test(r.path.trim()));
  if (!disallowsRoot) return false;
  // A narrower `Allow:` re-opens part of the site. Calling that "blocked" would tell an
  // owner they are invisible to ChatGPT when they are not — the worst mistake this file
  // can make, so the tie always goes to "not blocked".
  return !rules.some((r) => r.allow && r.path.trim().startsWith('/'));
}

export interface RobotsVerdict {
  /** The watched AI crawlers this file actually shuts out. */
  bots: string[];
  /** Whether the ban comes from the `User-agent: *` group — measured, never inferred. */
  viaWildcard: boolean;
  /** The `User-agent` values whose group carries the offending `Disallow`. */
  blockingAgents: string[];
}

/** The watched AI crawlers that this robots.txt actually shuts out. */
export function robotsBlocksAI(robotsTxt: string | null): string[] {
  return analyzeRobots(robotsTxt).bots;
}

/**
 * Who is blocked and, just as importantly, *where the block is written*. Deducing the
 * source from the count ("all twelve blocked, so it must be the wildcard") is wrong on the
 * most common shape there is: twelve per-bot groups plus a permissive `User-agent: *`. Get
 * that wrong and the report describes a line the file does not contain, while the suggested
 * fix rewrites rules the owner does want.
 */
export function analyzeRobots(robotsTxt: string | null): RobotsVerdict {
  const empty: RobotsVerdict = { bots: [], viaWildcard: false, blockingAgents: [] };
  if (!robotsTxt) return empty;
  // A soft 404 (the SPA's index.html served for /robots.txt) is not a robots policy.
  if (/^\s*(<!doctype|<html)/i.test(robotsTxt)) return empty;

  const groups = parseRobots(robotsTxt);
  const wildcard = groups.filter((g) => g.agents.includes('*'));
  const wildcardBlocks = wildcard.length > 0 && blocksEverything(wildcard.flatMap((g) => g.rules));

  const bots: string[] = [];
  const named = new Set<string>();
  for (const bot of AI_BOTS) {
    const own = groups.filter((g) => g.agents.includes(bot.toLowerCase()));
    // A group naming the bot wins outright: it is never merged with the `*` group.
    if (own.length > 0) {
      if (blocksEverything(own.flatMap((g) => g.rules))) {
        bots.push(bot);
        named.add(bot);
      }
      continue;
    }
    if (wildcardBlocks) bots.push(bot);
  }

  const blockingAgents = [...named];
  if (wildcardBlocks && bots.length > named.size) blockingAgents.push('*');

  return { bots, viaWildcard: wildcardBlocks && bots.length > named.size, blockingAgents };
}

// ---------------------------------------------------------------------------
// Findings
// ---------------------------------------------------------------------------

/**
 * Every check this module can emit, in report order. `checkWeb` only returns failures,
 * so the report needs this list to also show what passed — "6 of 18 checks passed" is
 * the line an owner acts on, and a report of nothing but problems reads as noise.
 * Keep in sync with the ids emitted below.
 */
export const WEB_CHECKS: { id: string; label: string }[] = [
  { id: 'web_robots_blocks_ai', label: 'robots.txt lets AI crawlers in' },
  { id: 'web_ai_block_incomplete', label: 'AI crawlers blocked as declared' },
  { id: 'web_empty_html', label: 'HTML carries real content' },
  { id: 'web_broken_assets', label: 'No broken assets' },
  { id: 'web_console_errors', label: 'No JavaScript errors on load' },
  { id: 'web_duplicate_titles', label: 'Each page has its own <title>' },
  { id: 'web_missing_title', label: '<title> present' },
  { id: 'web_missing_meta_description', label: 'Meta description' },
  { id: 'web_missing_og', label: 'Open Graph tags' },
  { id: 'web_missing_canonical', label: 'Canonical URL' },
  { id: 'web_missing_structured_data', label: 'Structured data (JSON-LD)' },
  { id: 'web_h1_structure', label: 'Exactly one <h1> per page' },
  { id: 'web_missing_sitemap', label: 'sitemap.xml' },
  { id: 'web_missing_llms_txt', label: 'llms.txt' },
  { id: 'web_missing_lang', label: 'lang attribute on <html>' },
  { id: 'web_missing_alt', label: 'Images have alt text' },
  { id: 'web_missing_404', label: 'Unknown URLs return 404' },
  { id: 'web_missing_favicon', label: 'Favicon' },
  { id: 'web_heavy_bundle', label: 'JavaScript under 1 MB' },
];

function formatBytes(bytes: number): string {
  if (bytes >= 1024 * 1024) return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
  if (bytes >= 1024) return `${Math.round(bytes / 1024)} KB`;
  return `${bytes} B`;
}

function ofPages(n: number, total: number): string {
  return `${n} of ${total} page${total === 1 ? '' : 's'}`;
}

function urlsOf(pages: PageSignals[]): string[] {
  return pages.map((p) => p.url);
}

function originOf(pages: PageSignals[]): string {
  const home = pages[0];
  if (!home) return 'https://example.com';
  try {
    return new URL(home.url).origin;
  } catch {
    return 'https://example.com';
  }
}

export function checkWeb(input: {
  pages: PageSignals[];
  files: SiteFiles;
  brokenAssets: BrokenAsset[];
  jsBytes: number;
  consoleErrors: ConsoleError[] | null;
  /** What the owner declared in vibeward.json, if anything. */
  intent?: VibewardIntent;
  /** Check ids that do not apply to this site. Never evaluated, never reported as ok. */
  notApplicable?: Map<string, string>;
}): Finding[] {
  const { pages, files, brokenAssets, jsBytes, consoleErrors, intent, notApplicable } = input;
  const findings: Finding[] = [];
  const origin = originOf(pages);
  const home = pages[0];
  const total = pages.length;

  const robots = analyzeRobots(files.robotsTxt);
  const blockedBots = robots.bots;

  // Declaring `aiCrawlers: "blocked"` does not silence the robots check, it inverts it: the
  // question stops being "are you shut out?" and becomes "are you shut out as thoroughly as
  // you think?". Believing you block AI while nine of twelve crawlers walk straight in is a
  // worse position than not having decided at all.
  if (intent?.aiCrawlers === 'blocked') {
    const open = AI_BOTS.filter((b) => !blockedBots.includes(b));
    if (open.length > 0) {
      findings.push({
        id: 'web_ai_block_incomplete',
        label: 'AI crawlers are not blocked as thoroughly as declared',
        severity: 'medium',
        kind: 'web',
        source: `${origin}/robots.txt`,
        evidence: `vibeward.json declares \`intent.aiCrawlers: "blocked"\`, but ${open.length} of ${AI_BOTS.length} watched AI crawlers are still allowed: ${open.join(', ')}.`,
        impact:
          'The content is being read and reused by the crawlers that were left out, which is exactly what the site set out to prevent — and nobody will notice, because the intention was recorded and never verified.',
        why: 'A partial block is the worst of both worlds: none of the visibility of being open, none of the protection of being closed.',
        fix: `Add the missing agents to robots.txt (\`public/robots.txt\` in most projects):

${open.map((b) => `User-agent: ${b}\nDisallow: /`).join('\n\n')}

robots.txt is a request, not a wall. Crawlers that ignore it need blocking at the CDN or the server.`,
        autofix: 'auto',
        references: ['https://www.rfc-editor.org/rfc/rfc9309'],
        meta: { count: open.length },
      });
    }
  }

  if (blockedBots.length > 0) {
    const { viaWildcard, blockingAgents } = robots;
    const where = blockingAgents.map((a) => `\`User-agent: ${a}\``).join(', ');
    findings.push({
      id: 'web_robots_blocks_ai',
      label: 'robots.txt blocks AI crawlers',
      severity: 'high',
      kind: 'web',
      source: `${origin}/robots.txt`,
      evidence: `robots.txt carries an effective \`Disallow: /\` under ${where}, which shuts out ${blockedBots.length} AI crawler${blockedBots.length === 1 ? '' : 's'}: ${blockedBots.join(', ')}.`,
      impact:
        'The site cannot be read by the assistants people now ask instead of Google, so it can never be cited, summarised or recommended in an AI answer. That referral channel is closed at the door.',
      why: 'Blocking these agents removes the site from ChatGPT, Claude, Perplexity and Google AI answers. It is one line in a text file, and it is usually there by copy-paste, not by decision.',
      // Surgical on purpose. This fix is `autofix: 'auto'`, so an agent applies it unattended:
      // handing it a whole replacement robots.txt would delete the Disallow rules the owner
      // does want (/admin, /checkout, staging) as a side effect of an SEO fix.
      fix: `In robots.txt (\`public/robots.txt\` in most projects), delete ONLY the \`Disallow: /\` line inside ${
        blockingAgents.length === 1 ? 'this group' : 'these groups'
      } and leave every other line exactly as it is:

${blockingAgents.map((a) => `User-agent: ${a}\n  Disallow: /        <- delete this line only`).join('\n\n')}
${
  viaWildcard
    ? `\nIf the intent was to keep some paths private, replace it with the specific ones (\`Disallow: /admin\`), never with a bare \`/\`.`
    : `\nAn empty \`Disallow:\` also works and is equivalent to allowing everything.`
}`,
      autofix: 'auto',
      references: [
        'https://platform.openai.com/docs/bots',
        'https://www.rfc-editor.org/rfc/rfc9309',
      ],
      meta: { count: blockedBots.length },
    });
  }

  const emptyPages = pages.filter((p) => p.bodyTextLength < EMPTY_HTML_CHARS);
  if (home && home.bodyTextLength < EMPTY_HTML_CHARS) {
    findings.push({
      id: 'web_empty_html',
      label: 'The HTML ships with no content',
      severity: 'high',
      kind: 'web',
      source: home.url,
      evidence: `The home page returns ${home.bodyTextLength} characters of visible text before JavaScript runs (${ofPages(emptyPages.length, total)} below ${EMPTY_HTML_CHARS} characters).`,
      impact:
        'To anything that does not run JavaScript the site is a blank page: no headline, no copy, nothing to index or quote. Most AI crawlers never execute scripts, so the site simply does not exist for them.',
      why: 'A client-rendered shell hands crawlers an empty <div>. Google renders eventually and inconsistently; GPTBot, ClaudeBot and PerplexityBot do not render at all.',
      fix: `Ship real HTML instead of an empty shell.

Cheapest fix, no framework change — put the real headline and first paragraph inside the mount node in \`index.html\` so it is in the source before any script runs:

<div id="root">
  <h1>Acme — bookkeeping for freelancers</h1>
  <p>One sentence saying what you do and who it is for.</p>
</div>

Proper fix — build the pages with a renderer that emits HTML: Astro, Next.js (\`app/\` server components) or Vite SSG.`,
      autofix: 'manual',
      meta: { pages: urlsOf(emptyPages), count: emptyPages.length },
    });
  }

  if (brokenAssets.length > 0) {
    const listed = brokenAssets.slice(0, 10);
    findings.push({
      id: 'web_broken_assets',
      label: 'Assets referenced by the site return an error',
      severity: 'high',
      kind: 'web',
      evidence: `${brokenAssets.length} referenced file${brokenAssets.length === 1 ? '' : 's'} answer with 4xx/5xx, e.g. ${listed
        .slice(0, 3)
        .map((a) => `${a.url} (${a.status})`)
        .join(', ')}.`,
      impact:
        'Visitors see missing images, unstyled sections or a feature that never loads — the fastest way to look abandoned and lose the sale on the first screen.',
      why: 'The page points at files that are not deployed: a path that only exists locally, a renamed asset, or an image the build never copied.',
      fix: `Fix the path or delete the tag for each of these:

${listed.map((a) => `- ${a.url} -> ${a.status} (referenced from ${a.from})`).join('\n')}${
        brokenAssets.length > listed.length
          ? `\n- …and ${brokenAssets.length - listed.length} more`
          : ''
      }

Assets served from the site root must live in \`public/\` (Vite, Next.js, Astro) or \`static/\` (SvelteKit) so the build copies them.`,
      autofix: 'auto',
      meta: { count: brokenAssets.length },
    });
  }

  if (consoleErrors !== null && consoleErrors.length > 0) {
    const listed = consoleErrors.slice(0, 5);
    findings.push({
      id: 'web_console_errors',
      label: 'The page throws JavaScript errors in the browser',
      severity: 'high',
      kind: 'web',
      source: home?.url,
      evidence: `${consoleErrors.length} console error${consoleErrors.length === 1 ? '' : 's'} on load: ${listed
        .map((e) => `[${e.type}] ${e.text.slice(0, 120)}`)
        .join(' | ')}`,
      impact:
        'Something on the page is already broken for every visitor — a form that never submits, a section that never appears. Whatever the error interrupts, the user never completes.',
      why: 'An uncaught exception stops the rest of that script. Errors on first load are not cosmetic: they usually mean a feature is dead.',
      fix: `Open the page with DevTools on the Console tab, reproduce, and fix the throwing code:

${listed.map((e) => `- [${e.type}] ${e.text.slice(0, 300)}`).join('\n')}${
        consoleErrors.length > listed.length
          ? `\n- …and ${consoleErrors.length - listed.length} more`
          : ''
      }`,
      autofix: 'manual',
      meta: { count: consoleErrors.length },
    });
  }

  const firstTitle = home?.title ?? null;
  if (total >= 2 && firstTitle && pages.every((p) => p.title === firstTitle)) {
    findings.push({
      id: 'web_duplicate_titles',
      label: 'Every page has the same <title>',
      severity: 'high',
      kind: 'web',
      evidence: `All ${total} crawled pages send the same title: "${firstTitle}".`,
      impact:
        'Every page competes for the same search result and none of them wins. The title is the blue line people click in Google and the label of every shared tab and bookmark.',
      why: 'Search engines treat identical titles as duplicate pages and pick one, dropping the rest. A one-page-app router that never updates the title is the usual cause.',
      fix: `Give every page its own <title> — 50-60 characters, the page subject first, the brand last:

<!-- /pricing -->
<title>Pricing — Acme</title>

React SPA without a meta framework, set it per route:

useEffect(() => { document.title = 'Pricing — Acme'; }, []);`,
      autofix: 'needs-input',
      meta: { pages: urlsOf(pages), count: total },
    });
  }

  const noTitle = pages.filter((p) => !p.title);
  if (home && !home.title) {
    findings.push({
      id: 'web_missing_title',
      label: 'The home page has no <title>',
      severity: 'high',
      kind: 'web',
      source: home.url,
      evidence: `${ofPages(noTitle.length, total)} have no <title> tag, including the home page.`,
      impact:
        'Google prints the URL or an invented phrase as the search result headline, and the browser tab reads as the bare domain. It is the single most visible piece of text the site owns.',
      why: 'The <title> is the headline of every search result, every shared link and every bookmark. Without it there is nothing to click.',
      fix: `Add a <title> to the <head> of every page:

<title>Acme — bookkeeping for freelancers</title>`,
      autofix: 'needs-input',
      meta: { pages: urlsOf(noTitle), count: noTitle.length },
    });
  }

  const noDescription = pages.filter((p) => !p.metaDescription);
  if (noDescription.length > 0) {
    findings.push({
      id: 'web_missing_meta_description',
      label: 'Pages have no meta description',
      severity: 'medium',
      kind: 'web',
      evidence: `${ofPages(noDescription.length, total)} have no <meta name="description">.`,
      impact:
        'Google fills the two lines under the link with whatever text it scrapes off the page, so the pitch a visitor reads before deciding to click is written by an algorithm instead of by the owner.',
      why: 'The description is the ad copy of the search result. It does not change ranking, it changes the click-through rate.',
      fix: `Add one description per page, 150-160 characters, written for a human deciding whether to click:

<meta name="description" content="Acme turns a folder of receipts into a monthly report in ten minutes. Built for freelancers who file their own taxes." />`,
      autofix: 'needs-input',
      meta: { pages: urlsOf(noDescription), count: noDescription.length },
    });
  }

  const noOg = pages.filter((p) => !p.ogTitle || !p.ogImage);
  if (noOg.length > 0) {
    findings.push({
      id: 'web_missing_og',
      label: 'Pages have no Open Graph tags',
      severity: 'medium',
      kind: 'web',
      evidence: `${ofPages(noOg.length, total)} are missing og:title or og:image.`,
      impact:
        'Shared on WhatsApp, LinkedIn, Slack or X the link renders as a naked URL with no image and no title, which people scroll past. Every share the site gets is wasted.',
      why: 'Open Graph tags are what social platforms and chat apps read to build the preview card. Without them there is no card.',
      fix: `Add the block to every page's <head> (og:image is a 1200x630 PNG):

<meta property="og:title" content="Acme — bookkeeping for freelancers" />
<meta property="og:description" content="Receipts in, monthly report out." />
<meta property="og:image" content="${origin}/og.png" />
<meta property="og:url" content="${origin}/" />
<meta property="og:type" content="website" />
<meta name="twitter:card" content="summary_large_image" />`,
      autofix: 'needs-input',
      references: ['https://ogp.me/'],
      meta: { pages: urlsOf(noOg), count: noOg.length },
    });
  }

  const noCanonical = pages.filter((p) => !p.canonical);
  if (noCanonical.length > 0) {
    findings.push({
      id: 'web_missing_canonical',
      label: 'Pages declare no canonical URL',
      severity: 'medium',
      kind: 'web',
      evidence: `${ofPages(noCanonical.length, total)} have no <link rel="canonical">.`,
      impact:
        'The same page reachable at www and non-www, with and without a trailing slash, or with a campaign parameter, is counted as several competing pages, splitting whatever authority the site has earned.',
      why: 'The canonical tag names the one real address of a page so duplicates consolidate into it instead of competing with it.',
      fix: `Add one canonical per page, pointing at that page's own absolute URL:

<link rel="canonical" href="${origin}/pricing" />`,
      autofix: 'auto',
      references: [
        'https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls',
      ],
      meta: { pages: urlsOf(noCanonical), count: noCanonical.length },
    });
  }

  const noJsonLd = pages.filter((p) => p.jsonLdBlocks === 0);
  if (noJsonLd.length > 0) {
    findings.push({
      id: 'web_missing_structured_data',
      label: 'No structured data (JSON-LD)',
      severity: 'medium',
      kind: 'web',
      evidence: `${ofPages(noJsonLd.length, total)} contain no <script type="application/ld+json"> block.`,
      impact:
        'Search engines and assistants have to guess what the business is, what it sells and where it is. Rich results (ratings, prices, FAQ, opening hours) are not available to a site that never declares them.',
      why: 'Structured data is the machine-readable version of the page. It is how an assistant answers "who are they and what do they do" with facts instead of guesses.',
      fix: `Add one JSON-LD block to the home page <head> and adjust the values:

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Organization",
  "name": "Acme",
  "url": "${origin}",
  "logo": "${origin}/logo.png",
  "description": "Bookkeeping for freelancers.",
  "sameAs": ["https://www.linkedin.com/company/acme"]
}
</script>`,
      autofix: 'needs-input',
      references: ['https://schema.org/Organization'],
      meta: { pages: urlsOf(noJsonLd), count: noJsonLd.length },
    });
  }

  const noH1 = pages.filter((p) => p.h1Count === 0);
  const manyH1 = pages.filter((p) => p.h1Count > 1);
  if (noH1.length > 0 || manyH1.length > 0) {
    const parts: string[] = [];
    if (noH1.length > 0) parts.push(`${ofPages(noH1.length, total)} have no <h1>`);
    if (manyH1.length > 0) {
      parts.push(
        `${ofPages(manyH1.length, total)} have more than one (up to ${Math.max(...manyH1.map((p) => p.h1Count))})`,
      );
    }
    findings.push({
      id: 'web_h1_structure',
      label: 'Heading structure is wrong',
      severity: 'medium',
      kind: 'web',
      evidence: `${parts.join('; ')}.`,
      impact:
        'The one line that tells a search engine, an assistant and a screen reader what the page is about is missing or repeated, so the page is filed under the wrong subject or under none.',
      why: 'Exactly one <h1> per page, carrying the subject of that page. Extra ones are usually styling choices, not headings.',
      fix: `One <h1> per page, containing the subject of that page:

<h1>Pricing</h1>

Demote the extra <h1> tags to <h2> and keep the styling with a class.

Pages with none: ${noH1.length > 0 ? urlsOf(noH1).join(', ') : '(none)'}
Pages with several: ${manyH1.length > 0 ? manyH1.map((p) => `${p.url} (${p.h1Count})`).join(', ') : '(none)'}`,
      autofix: 'needs-input',
      meta: { pages: [...urlsOf(noH1), ...urlsOf(manyH1)], count: noH1.length + manyH1.length },
    });
  }

  if (!files.sitemapXml) {
    findings.push({
      id: 'web_missing_sitemap',
      label: 'No sitemap.xml',
      severity: 'medium',
      kind: 'web',
      source: `${origin}/sitemap.xml`,
      evidence: `${origin}/sitemap.xml is not served.`,
      impact:
        'Pages that are not linked from the home page can go unnoticed for weeks or never get indexed at all, and every update takes longer to show up in search.',
      why: 'A sitemap is the list of pages the owner wants indexed. Without it crawlers only find what they happen to stumble on.',
      fix: `Create \`public/sitemap.xml\` (\`static/sitemap.xml\` on SvelteKit) with the pages found while crawling:

<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${(total > 0 ? urlsOf(pages) : [`${origin}/`]).map((u) => `  <url><loc>${u}</loc></url>`).join('\n')}
</urlset>

Then point robots.txt at it:

Sitemap: ${origin}/sitemap.xml`,
      autofix: 'auto',
      references: ['https://www.sitemaps.org/protocol.html'],
    });
  }

  if (!files.llmsTxt) {
    findings.push({
      id: 'web_missing_llms_txt',
      label: 'No llms.txt',
      severity: 'medium',
      kind: 'web',
      source: `${origin}/llms.txt`,
      evidence: `${origin}/llms.txt is not served.`,
      impact:
        'When an assistant is asked about this business it has to reconstruct the offer from whatever markup it can parse. A short curated file is the difference between being described accurately and being described wrong.',
      why: 'llms.txt is the plain-text summary an AI reads first: what the site is, who it is for, and which pages matter.',
      fix: `Create \`public/llms.txt\` and replace the placeholders with the real offer:

# Acme
> One sentence on what the site offers and who it is for.

Acme does X for Y. Based in Z. Contact: hello@example.com

## Pages
${(total > 0 ? pages : []).map((p) => `- [${p.title ?? 'Page'}](${p.url}): what this page covers`).join('\n') || `- [Home](${origin}/): what this page covers`}`,
      autofix: 'needs-input',
      references: ['https://llmstxt.org/'],
    });
  }

  const noLang = pages.filter((p) => !p.lang);
  if (noLang.length > 0) {
    findings.push({
      id: 'web_missing_lang',
      label: 'The <html> tag declares no language',
      severity: 'medium',
      kind: 'web',
      evidence: `${ofPages(noLang.length, total)} have no lang attribute on <html>.`,
      impact:
        'Browsers offer to translate a page that is already in the language of the visitor, screen readers pick the wrong voice, and search engines can serve the site to the wrong country.',
      why: 'One attribute tells every client what language the content is written in. Templates ship with it empty or copied from the starter.',
      fix: `Set the language the content is actually written in:

<html lang="en">`,
      autofix: 'auto',
      meta: { pages: urlsOf(noLang), count: noLang.length },
    });
  }

  const imgTotal = pages.reduce((n, p) => n + p.imgTotal, 0);
  const imgWithoutAlt = pages.reduce((n, p) => n + p.imgWithoutAlt, 0);
  if (imgTotal > 0 && imgWithoutAlt > 0) {
    const affected = pages.filter((p) => p.imgWithoutAlt > 0);
    findings.push({
      id: 'web_missing_alt',
      label: 'Images have no alt text',
      severity: 'medium',
      kind: 'web',
      evidence: `${imgWithoutAlt} of ${imgTotal} images have no alt attribute, across ${ofPages(affected.length, total)}.`,
      impact:
        'Blind visitors hear "image" instead of the product, image search never returns these pictures, and in several jurisdictions it is an accessibility obligation rather than a nicety.',
      why: 'Alt text is what an image says to anyone or anything that cannot see it: screen readers, image search, and any crawler indexing the page.',
      fix: `Describe what the image shows, in the page's language:

<img src="/team.jpg" alt="The Acme team in their Lima office" />

Use \`alt=""\` (empty, not missing) only for decoration such as background shapes or icons next to text that already says the same thing.`,
      autofix: 'needs-input',
      meta: { pages: urlsOf(affected), count: imgWithoutAlt },
    });
  }

  const probe = files.notFound;
  if (probe.status > 0 && (probe.status < 400 || !probe.distinct)) {
    findings.push({
      id: 'web_missing_404',
      label: 'Unknown URLs do not return a real 404',
      severity: 'low',
      kind: 'web',
      source: `${origin}/vibeward-404-probe`,
      evidence:
        probe.status < 400
          ? `A URL that does not exist answered ${probe.status} instead of 404${probe.distinct ? '' : ' and served the home page'}.`
          : `The 404 response body is the same page as the home page.`,
      impact:
        'Search engines index infinite non-existent URLs as copies of the home page, and a visitor who mistypes a link lands on something that looks fine but is not the page they wanted.',
      why: 'A single-page app that serves index.html for every path never tells anyone that a URL is wrong. The status code is the signal, not the design.',
      fix: `Add a 404 page and let unknown paths answer 404.

Static host (Netlify, Cloudflare Pages, GitHub Pages, Firebase Hosting) — create \`public/404.html\`:

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Page not found</title>
    <meta name="robots" content="noindex" />
  </head>
  <body>
    <h1>Page not found</h1>
    <p><a href="/">Back to the home page</a></p>
  </body>
</html>

Next.js — create \`app/not-found.tsx\`.
React SPA — add a catch-all route: <Route path="*" element={<NotFound />} />`,
      autofix: 'auto',
    });
  }

  if (!files.faviconOk && !pages.some((p) => p.faviconLink)) {
    findings.push({
      id: 'web_missing_favicon',
      label: 'No favicon',
      severity: 'low',
      kind: 'web',
      source: `${origin}/favicon.ico`,
      evidence: 'No favicon is served and no <link rel="icon"> is declared on any crawled page.',
      impact:
        'The tab, the bookmark and the phone home screen show a blank sheet of paper. It is small, it is free to fix, and it is the difference between a business and a weekend demo.',
      why: 'The favicon is the only branding a site gets in a row of thirty open tabs.',
      fix: `Add \`public/favicon.svg\` (and a 180x180 \`public/apple-touch-icon.png\`), then reference them in <head>:

<link rel="icon" href="/favicon.svg" type="image/svg+xml" />
<link rel="apple-touch-icon" href="/apple-touch-icon.png" />`,
      autofix: 'needs-input',
    });
  }

  if (jsBytes > HEAVY_BUNDLE_BYTES) {
    findings.push({
      id: 'web_heavy_bundle',
      label: 'JavaScript payload is heavy',
      severity: 'low',
      kind: 'web',
      evidence: `${formatBytes(jsBytes)} of uncompressed JavaScript is downloaded to render the page (threshold: 1.0 MB).`,
      impact:
        'On a mid-range phone over mobile data the page stays blank for seconds, and a large share of visitors leave before it paints — they never see the offer at all.',
      why: 'Everything in the entry bundle blocks the first render, including code for routes the visitor may never open.',
      fix: `Find what is heavy, then split it:

npx vite-bundle-visualizer                       # Vite
npx source-map-explorer 'build/static/js/*.js'   # Create React App

Lazy-load anything not needed for the first paint:

const Chart = React.lazy(() => import('./Chart'));`,
      autofix: 'manual',
      meta: { count: jsBytes },
    });
  }

  // Filtered at the end rather than guarded at every push: one place to look, and a new
  // check can never forget to honour the config.
  return notApplicable ? findings.filter((f) => !notApplicable.has(f.id)) : findings;
}
